### ISSUE TITLE
subbuffers?

### ISSUE THREAD

**Issue by hughperkins** [inducer/pyopencl#154]
Checked the doc, and grepped site-packages/pyopencl.  Seems like dont currently exist in pyopencl?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

https://documen.tician.de/pyopencl/runtime_memory.html#pyopencl.Buffer.__getitem__

**Comment by hughperkins** [comment]
Hmmm, good point.  Thanks! :-)
