### ISSUE TITLE
Provide Module for Scalar dtype

### ISSUE THREAD

**Issue by JonnoFTW** [inducer/pyopencl#159]
Similar to how `cl.array.vec` provides the various vector types (`float2`..`float32` etc.), can a module be provided that provides the scalar data types?

It's annoying having to remember that a cl `float` is actually a `numpy.float32` and not a `numpy.float`, plus it would be more convenient.

Usage would look something like:

    import pyopencl as cl
    from pyopencl import dtypes
    some_val = cl.dtypes.ushort(120)

**Comment by inducer** [comment]
Not a bad idea. I'd be happy to take a patch.

**Comment by JonnoFTW** [comment]
@inducer would `cl.ushort` be acceptable? This keeps in line with how numpy does provides its types.

**Comment by inducer** [comment]
Gut feeling: no, since it's inconsistent with where the vector types live (do you want to make those available there, too?).

**Comment by inducer** [comment]
Could be convinced though.

**Comment by JonnoFTW** [comment]
I guess this would be an all or nothing change. Either types go in `cl` or go in their own module.

Pros of using `cl`:
 * Consistent with numpy
Cons:
 * Inconsistent with existing pyopencl design
 * Managing backwards compatibility is awkward (would be providing the same thing in two places), this is the most significant issue

I guess after reflection there should be a separate module for types.

**Comment by JonnoFTW** [comment]
@inducer any thoughts on my latest update?

**Comment by inducer** [comment]
Sorry, my life's been a mess the past month. I'm hoping to be able to take a look this weekend.
