### ISSUE TITLE
pyopencl - 2016.2.1 VS2015 Update 3 fails compilation

### ISSUE THREAD

**Issue by acpopescu** [inducer/pyopencl#161]
Hello!

Building pyopencl with pytrhon3.6, VS2015 update 3, with or without GL support using the intel OpenCL SDK fails with an internal compiler error (also tested without std C++14 flag):

C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 "-IC:\Program Files (x86)\Intel\OpenCL SDK\include" -Isrc/c_wrapper/ -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\winrt" /EHsc /Tpsrc/c_wrapper/wrap_cl.cpp /Fobuild\temp.win-amd64-3.6\Release\src/c_wrapper/wrap_cl.obj /std:c++14
wrap_cl.cpp
d:\tmp\pyopencl-2016.2.1\src\c_wrapper\utils.h(226): warning C4800: 'cl_bool': forcing value to bool 'true' or 'false' (performance warning)
src/c_wrapper/wrap_cl.cpp(58): warning C4800: 'clobj_t': forcing value to bool 'true' or 'false' (performance warning)
src/c_wrapper/wrap_cl.cpp(100): warning C4800: 'int': forcing value to bool 'true' or 'false' (performance warning)
d:\tmp\pyopencl-2016.2.1\src\c_wrapper\function.h(79): fatal error C1001: An internal error has occurred in the compiler.
(compiler file 'f:\dd\vctools\compiler\cxxfe\sl\p1\c\outdname.c', line 4869)
 To work around this problem, try simplifying or changing the program near the locations listed above.
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
d:\tmp\pyopencl-2016.2.1\src\c_wrapper\error.h(191): note: see reference to class template instantiation 'ArgPack<CLArg,_cl_device_id *const >' being compiled
d:\tmp\pyopencl-2016.2.1\src\c_wrapper\error.h(242): note: see reference to class template instantiation 'CLArgPack<_cl_device_id *const >' being compiled
d:\tmp\pyopencl-2016.2.1\src\c_wrapper\device.h(36): note: see reference to function template instantiation 'void call_guarded<const CLType&,cl_device_id>(cl_int (__cdecl *)(cl_device_id),const char *,const CLType &)' being compiled
        with
        [
            CLType=cl_device_id
        ]

**Comment by inducer** [comment]
Known problem, see also https://github.com/conda-forge/staged-recipes/pull/1762. The only known workaround is to downgrade to Update 2. Maybe the [pre-built conda-forge packages](https://anaconda.org/conda-forge/pyopencl) will work for your use case? Or the ones by Christoph Gohlke?

**Comment by acpopescu** [comment]
Cool, thanks for the update!

Using Cristolph's pre-built binaries did the trick for me. Thanks!
