### ISSUE TITLE
RadixSort compilation fails on AMD Radeon R9 M370X in OS X 10.11.6 (Xcode 8.2.1) 

### ISSUE THREAD

**Issue by hightower8083** [inducer/pyopencl#162]
Hi, sorry to bother (probably its not a right place for this question), but I can't get RadixSort compiled on my MacPro's AMD Radeon GPU. It works like charm on CPU of the same machine, so its not a general openCL issue (i've OS X 10.11.6 with Xcode 8.2.1). I've failed to localise the problem better than that -- most other algos seem working fine (Bitonic, GenericScan etc), but in my work I need a more generic sort than bitonic. Here is a simple test -- CPU does compile with minor warnings, but GPU fails completely, with a rather dry output:

```python
import pyopencl as cl
from pyopencl.algorithm import RadixSort
cl.create_some_context(interactive=True)
```

    Choose platform:
    [0] <pyopencl.Platform 'Apple' at 0x7fff0000>
    Choice [0]:0
    Choose device(s):
    [0] <pyopencl.Device 'Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz' on 'Apple' at 0xffffffff>
    [1] <pyopencl.Device 'Iris Pro' on 'Apple' at 0x1024500>
    [2] <pyopencl.Device 'AMD Radeon R9 M370X Compute Engine' on 'Apple' at 0x1021c00>
    Choice, comma-separated [0]:0
    Set the environment variable PYOPENCL_CTX='0:0' to avoid being asked again.

    <pyopencl.Context at 0x7fcfdb5e65f0 on <pyopencl.Device 'Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz' on 'Apple' at 0xffffffff>>

```python
ctx = cl.create_some_context(answers=[0,0])
sort = RadixSort(ctx, "int *indx_in_cell",
                 key_expr="indx_in_cell[i]",
                 sort_arg_names=["indx_in_cell",]);
```

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/cffi_cl.py:1476: CompilerWarning: Non-empty compiler output encountered. Set the environment variable PYOPENCL_COMPILER_OUTPUT=1 to see more.
      "to see more.", CompilerWarning)

```python
ctx = cl.create_some_context(answers=[0,2])
sort = RadixSort(ctx, "int *indx_in_cell",
                 key_expr="indx_in_cell[i]",
                 sort_arg_names=["indx_in_cell",]);
```

    ---------------------------------------------------------------------------

    RuntimeError                              Traceback (most recent call last)

    <ipython-input-3-3c2a8b27ba74> in <module>()
          2 sort = RadixSort(ctx, "int *indx_in_cell",
          3                  key_expr="indx_in_cell[i]",
    ----> 4                  sort_arg_names=["indx_in_cell",]);
    

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/algorithm.pyc in __init__(***failed resolving arguments***)
        487                 neutral="scan_t_neutral()",
        488                 output_statement=RADIX_SORT_OUTPUT_STMT_TPL.render(**codegen_args),
    --> 489                 preamble=scan_preamble, options=self.options)
        490 
        491         for i, arg in enumerate(self.arguments):

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/scan.pyc in __init__(self, ctx, dtype, arguments, input_expr, scan_expr, neutral, output_statement, is_segment_start_expr, input_fetch_exprs, index_dtype, name_prefix, options, preamble, devices)
       1031         # }}}
       1032 
    -> 1033         self.finish_setup()
       1034 
       1035     # }}}

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/scan.pyc in finish_setup(self)
       1124                     store_segment_start_flags=self.store_segment_start_flags,
       1125                     k_group_size=k_group_size,
    -> 1126                     use_bank_conflict_avoidance=use_bank_conflict_avoidance)
       1127 
       1128             # Will this device actually let us execute this kernel

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/scan.pyc in build_scan_kernel(self, max_wg_size, arguments, input_expr, is_segment_start_expr, input_fetch_exprs, is_first_level, store_segment_start_flags, k_group_size, use_bank_conflict_avoidance)
       1276             **self.code_variables))
       1277 
    -> 1278         prg = cl.Program(self.context, scan_src).build(self.options)
       1279 
       1280         knl = getattr(prg, kernel_name)

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/__init__.pyc in build(self, options, devices, cache_dir)
        436                         self._context, self._source, options_bytes, devices,
        437                         cache_dir=cache_dir, include_path=include_path),
    --> 438                     options_bytes=options_bytes, source=self._source)
        439 
        440             del self._context

    /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/__init__.pyc in _build_and_catch_errors(self, build_func, options_bytes, source)
        471         # Python 3.2 outputs the whole list of currently active exceptions
        472         # This serves to remove one (redundant) level from that nesting.
    --> 473         raise err
        474 
        475     # }}}

    RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - 
    
    Build on <pyopencl.Device 'AMD Radeon R9 M370X Compute Engine' on 'Apple' at 0x1021c00>:
    
    Error returned by cvms_element_build_from_source
    (options: -I /usr/local/lib/python2.7/site-packages/pyopencl-2016.2.1-py2.7-macosx-10.11-x86_64.egg/pyopencl/cl)
    (source saved as /var/folders/xr/pdv4v0rn14j_yf89p0h9np_c0000gn/T/tmpRA1ZWv.cl)

```python

```

Thanx in advance

**Comment by inducer** [comment]
Thanks for reporting this. It's a known issue. An Apple compiler bug we can't do much about without more specific info than "it crashed".

**Comment by hightower8083** [comment]
Well can it be helpful to know that replacing the default argument of  RadixSort, "scan_kernel=GenericScanKernel" by "scan_kernel=GenericDebugScanKernel" actually has resolved this issue? It works super-slow, but correctly.
Would be glad to somehow help more to resolve this issue..

**Comment by inducer** [comment]
It would be helpful to identify what parts of the kernel are making the compiler crash. I.e. open up `pyopencl/scan.py` and remove parts of the code until you have something that compiles, and report what part (e.g. what type declaration, or whatever) led to the crash.

**Comment by hightower8083** [comment]
crash happens, on initialisation, when  ```_GenericScanKernelBase``` calls method 
```finish_setup()``` of ```GenericScanKernel``` class, and it tries to run 
```candidate_scan_info = self.build_scan_kernel(...)```

 In this function the crash occurs when it actually compiles the program (line 1278 of scan.py)
```prg = cl.Program(self.context, scan_src).build(self.options)```

The rendered ```scan_src``` is obviously too big to put here, but the device-dependent args seem to be only
```wg_size, k_group_size, use_bank_conflict_avoidance```:
CPU gets them as
```
8 128 0
1 128 0
1 128 0
```

and GPU gets ```256 4 4``` and than dies (just guessing that those are responsible)

**Comment by inducer** [comment]
Thanks for doing that. I'm more interested in determining what parts of the C source code are causing trouble, though. Could you try commenting out bits and pieces of that until you determine a culprit?

Sorry for not being sufficiently clear initially.

**Comment by hightower8083** [comment]
When I construct 
```sort = RadixSort(ctx, "int *a", key_expr="a[i]",sort_arg_names="a");```

the ```candidate_scan_info``` of ```GenericScanKernel``` compiles the code ```scan_src``` and the compilation  crashes at 
```
            // {{{ psc_carry in from previous unit, if applicable


            if (psc_LID_0 == 0 && psc_unit_base != psc_interval_begin)
            {
                psc_ldata[0][0].psc_value = psc_SCAN_EXPR(
                    psc_ldata[psc_K][psc_WG_SIZE - 1].psc_value, psc_ldata[0][0].psc_value,
                        false
                    );
            }

            pycl_printf(("after psc_carry-in\n"));
```

Its not far from the beginning of kernel definition (line 202 of ```scan_src```)

**Comment by hightower8083** [comment]
btw, its a first use of ```psc_SCAN_EXPR``` in the kernel, so there might be a problem with it. This is how it is defined 
```#define psc_SCAN_EXPR(a, b, across_seg_boundary) scan_t_add(a, b, across_seg_boundary)```
and 
```
    scan_t scan_t_add(scan_t a, scan_t b, bool across_seg_boundary)
    {

            b.c00 = a.c00 + b.c00;

            b.c01 = a.c01 + b.c01;

            b.c10 = a.c10 + b.c10;

            b.c11 = a.c11 + b.c11;

        return b;
    }
```
Its data type is defined like 
```typedef pyopencl_sort_scan_int32_2bits_t scan_t;```
which is also used in the function ```scan_t_from_value``` which is used before and do not cause the crash

Feel free to propose some more tests if this could help to make thing work

**Comment by inducer** [comment]
Could you try simplifying the C code until it works, so that we know what the compiler is having trouble with? (The source gets written to `/tmp`.) Just start from that and feed modified versions of it to a compile script (say, derived from `examples/demo.py`) until the compiler stops dying.

**Comment by hightower8083** [comment]
Well, I probably have not been clear, but this is exactly what I've done:
- I've  run ```sort = RadixSort(ctx, "int *a", key_expr="a[i]",sort_arg_names="a");``` so it has crashed 
- I've copied the  generated source file as ```tst.cl```  and have been test-compiling it with 
```cl.Program(ctx,open('/.../tst.cl').read()).build()```
- I was gradually removing the code inside kernel definition (starting from its end), i.e. one that follows 
```
KERNEL
REQD_WG_SIZE(psc_WG_SIZE, 1, 1)
void scan_scan_intervals_lev1(...)
{ ...
```
- compilation have stopped crashing when I've removed everything after (almost the whole code basically)
```
            // {{{ read a unit's worth of data from psc_global

            for(psc_index_type psc_k = 0; psc_k < psc_K; psc_k++)
            {
                const psc_index_type psc_offset = psc_k*psc_WG_SIZE + psc_LID_0;
                const psc_index_type psc_read_i = psc_unit_base + psc_offset;

                {

                    psc_scan_type psc_scan_value = psc_INPUT_EXPR(psc_read_i);

                    const psc_index_type psc_o_mod_k = psc_offset % psc_K;
                    const psc_index_type psc_o_div_k = psc_offset / psc_K;
                    psc_ldata[psc_o_mod_k][psc_o_div_k].psc_value = psc_scan_value;

                }
            }

            pycl_printf(("after read from psc_global\n"));

            // }}}
```
- crashing re-starts as soon as I add the lines (which follow it in original source)
```
            // {{{ psc_carry in from previous unit, if applicable


            if (psc_LID_0 == 0 && psc_unit_base != psc_interval_begin)
            {
                psc_ldata[0][0].psc_value = psc_SCAN_EXPR(
                    psc_ldata[psc_K][psc_WG_SIZE - 1].psc_value, psc_ldata[0][0].psc_value,
                        false
                    );
            }

            pycl_printf(("after psc_carry-in\n"));
```
- the returned error message is useless
```RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - ```
- so I assume that kernel dies as soon as the function ```psc_SCAN_EXPR``` is called

**Comment by hightower8083** [comment]
Hi Andreas. 
I think I've found a roundabout for this issue with ```GenericScanKernel```. Actually, ```SCAN_EXPR()``` simply doesn't like to take the arguments in the form of ```psc_ldata[][].psc_value``` , because of their type (seems crazy but it is so):
- the variable ```ldata``` is defined as 
```LOCAL_MEM struct wrapped_scan_type ldata[K + 1][WG_SIZE + 1];```
and its type is defined as
```
        struct __attribute__ ((__packed__)) wrapped_scan_type
        {
            scan_type value;
            int dummy;
        };
```
so ```psc_ldata[][].psc_value``` definitively has a type ```scan_type``` which should be good for ```SCAN_EXPR()```, but somehow it crashes the compilation

The issue can be fixed by defining the temporal ```scan_t```-type arguments for ```SCAN_EXPR()```, i.e. replacing (scan.py line 298):
```
                ldata[0][0].value = SCAN_EXPR(
                    ldata[K][WG_SIZE - 1].value, ldata[0][0].value,
                    %if is_segmented:
                        (l_segment_start_flags[0][0])
                    %else:
                        false
                    %endif
                    );
```
with 
```
                scan_type tmp_var_1 = ldata[0][0].value;
                scan_type tmp_var_2 = ldata[K][WG_SIZE - 1].value;
                ldata[0][0].value = SCAN_EXPR(
                    tmp_var_2,tmp_var_1,
                    %if is_segmented:
                        (l_segment_start_flags[0][0])
                    %else:
                        false
                    %endif
                    );
```

With this, the RadixSort works for both CPU and GPU on my Mac (GPU goes 2-3 times faster than CPU), and it has fixed 4 fails in ```test_algorithm.py```, though there are 3 more which are associated with complex64 bug. Let me know if this solution seems good to you, and if you want I could do a PR.

**Comment by inducer** [comment]
Thanks for doing this detective work! Please do send a PR, I'd be delighted to take that. I simply haven't had the time to go hunting for a workaround, so I appreciate that you've done all this.

**Comment by hightower8083** [comment]
Was glad to help. I've made a PR to the master branch. Wish fixing the complex types on Apple AMD would be as easy as this one =).

**Comment by inducer** [comment]
See #167.
