### ISSUE TITLE
double3 argument seems to screw up subsequent arguments on some machines

### ISSUE THREAD

**Issue by smheidrich** [inducer/pyopencl#164]
Example code which works fine on some machines and fails on others:
````python
import numpy as np
import pyopencl as cl
from pyopencl import array as cl_arr
from pyopencl.array import vec as cl_vec

cl_ctx = cl.create_some_context()
cl_queue = cl.CommandQueue(cl_ctx)

prg = cl.Program(cl_ctx,
"""
__kernel void test_func(__global int *arr, double3 sca, __global int* out) {
        size_t i = get_global_id(0);
        out[i] = 1;
}
""")
prg = prg.build()

arr = cl_arr.to_device(cl_queue, np.zeros(10, dtype=np.int32))
sca = cl_vec.make_double3(1.,2.,3.)
out = cl_arr.to_device(cl_queue, np.zeros(10, dtype=np.int32))
print(out.get()) # should be: 0 0 0 0 0 0 0 0 0 

prg.test_func(cl_queue, arr.shape, None, arr.data, sca, out.data)

print(out.get()) # should be: 1 1 1 ..., but sometimes is 0 0 0 ... instead
````
It seems that sometimes there is nothing at all written to the ``out`` buffer and it stays *zero-ed*.

Replacing ``double3`` with ``float3`` makes it work fine.

Curiously, replacing it with ``double4`` not only makes it work fine for this call, but also for subsequent calls where it has been replaced back again to ``double3``. Executing a different PyOpenCL program resets this, after which it will fail again with ``double3``. (Yeah pretty weird.)

So to me it seems this is most likely caused by the second argument overwriting the third due to wrong specified size, or something of that nature. Then the address pointed to by ``out`` will be wrong, hence the changes written there won't be visible "from the outside" (Python code that prints ``out``). Or am I doing something wrong here?

I wrote an equivalent test case in pure C and it works fine there, so most likely the bug is in PyOpenCL and not in the OpenCL implementation that I'm using.

I haven't yet been able to figure out what the defining characteristic of a machine on which this fails is, but will comment here once I have.

**Comment by inducer** [comment]
It seems that in your program you are trying to write 10 `double3`s into space that's sufficient for 10 `int32`s. Or am I missing something?

**Comment by smheidrich** [comment]
@inducer Where? I don't see it. The ``out`` array is filled with a sequence of 10 ordinary integer ``1``s. The ``double3`` argument to the kernel isn't actually used for anything, it's just there to make the bug (if it is in fact one) appear.

**Comment by inducer** [comment]
Ah, nvm.

I've tested this across these implementations:

```
[0] <pyopencl.Platform 'NVIDIA CUDA' at 0x55a3752a9dc0>
[1] <pyopencl.Platform 'AMD Accelerated Parallel Processing' at 0x7fe06290b430>
[2] <pyopencl.Platform 'Portable Computing Language' at 0x7fe05de38070>
[3] <pyopencl.Platform 'Intel(R) OpenCL' at 0x55a3752aaed0>
```

(on 64-bit Linux), and I have not once seen the issue you describe. In addition, since the underlying OpenCL C API sets arguments by number, there is very little opportunity for PyOpenCL to screw anything up...

I'm not doubting what you're seeing, however I don't quite see how PyOpenCL could be contributing. Sorry!

**Comment by smheidrich** [comment]
All right, thank you very much for investigating! I'll look into other possible causes of this.
