### ISSUE TITLE
INVALID_OPERATION after call to `cl.array.zeros` on NVidia GeForce 580 GTX

### ISSUE THREAD

**Issue by whitespacer** [inducer/pyopencl#168]
On NVidia GeForce 580 GTX call to function `cl.array.zeros` leads to error INVALID_OPERATION after inside `clEnqueueFillBuffer` is called.
On other computer with NVidia GeForce 680 GTX everything works okay.

What I think is happening - PyOpenCL checks platform version instead of device version:
1) My platform supports cl 1.2
2) NVidia GeForce 580 GTX supports only cl 1.1 (which is correctly reported by call to `devices[0].get_info(cl.device_info.VERSION`))
3) `cl.array.zeros` insides calls `_zero_fill`
(see https://github.com/pyopencl/pyopencl/blob/c678bb96323d60a04374f1142a08422cee974793/pyopencl/array.py#L1170)
4) `_zero_fill` checks cl version with `queue._get_cl_version() >= (1, 2) and cl.get_cl_header_version() >= (1, 2)`
5) `cl.get_cl_header_version()` obviously returns 1.2
6) `queue._get_cl_version()` returns 1.2. Probably it should return 1.1, because it has device which supports only cl 1.1. However queue returns platform cl version
(see https://github.com/pyopencl/pyopencl/blob/87fec9cba500a6aff47b7c0367c7663b4938404f/pyopencl/cffi_cl.py#L786)

**Comment by inducer** [comment]
Excellent detective work! Could you try and see if the above commit fixes it?

**Comment by whitespacer** [comment]
Thanks for fast fixing! I've tried - it works!
