### ISSUE TITLE
Typo in ListOfListsBuilder lsize computation

### ISSUE THREAD

**Issue by mattwala** [inducer/pyopencl#175]
Pretty sure this line should say `queue.device.type & cl.device_type.CPU`:

https://github.com/pyopencl/pyopencl/blob/0a33373ddbaa8a486486bd65897a4264af4c7741/pyopencl/algorithm.py#L1042

Otherwise, it ends up computing the lsize to be different from reqd_work_group_size.

**Comment by mattwala** [comment]
Actually, it should probably just use `do_not_vectorize()` in the check to be on the safe side.

**Comment by inducer** [comment]
Thanks for figuring this out!
