### ISSUE TITLE
Segfaults with gl_interop_demo.py

### ISSUE THREAD

**Issue by SleepProgger** [inducer/pyopencl#177]
I am experiencing segfaults when trying to use OpenGl and pyopencl together.
Both are working fine without the other.

The [gl_interop_demo](https://github.com/pyopencl/pyopencl/blob/master/examples/gl_interop_demo.py) segfaults without changes.
When moving the `cl.get_platforms()` calls before the `glutCreateWindow` call and provide my platform as argument to the `initialize` function the segfault goes away but the `cl.Context` init function raises:
`pyopencl.cffi_cl.LogicError: clCreateContext failed: <unknown error -64>`

The same happens with [this](http://cyrille.rossant.net/a-tutorial-on-openglopencl-interoperability-in-python/) code.  Additionally the segfault also happens in combination with kivy.

I am running debian stretch.
PyOpencl version:  2016.1+git20161130-1
In the hope it helps:
["clinfo" output](https://pastebin.com/yM1Uwj9W)
["glxinfo -B -l" output](https://pastebin.com/XMCUj1Yn)

If required i could run it via strace (or what ever could help).

*Code to reproduce segfault.*
Move the cl.get_platforms call up one line to see error -64 thing.

```

if __name__ == '__main__':
    import sys
    import pyopencl as cl
    from OpenGL.GLUT import *
    import pyopencl as cl
    from pyopencl.tools import get_gl_sharing_context_properties
    
    glutInit(sys.argv)
    glutCreateWindow('OpenCL/OpenGL Interop Tutorial: Sin Generator')
    platform = cl.get_platforms()[0]
    
    try:
        ctx = cl.Context(properties=[
            (cl.context_properties.PLATFORM, platform)]
            + get_gl_sharing_context_properties())
    except:
        ctx = cl.Context(properties=[
            (cl.context_properties.PLATFORM, platform)]
            + get_gl_sharing_context_properties(),
            devices = [platform.get_devices()[0]])
    glutMainLoop()
```

**Comment by SleepProgger** [comment]
I just discovered my devices/driver doesn't support the `cl_khr_gl_sharing` extension, so the failing to get a context is to be expected.

After reading a bit about the status of the Mesa/GalliumCompute driver i don't think pyopencl is at fault here.
Sorry for the noise.
<hr>
As a workaround regarding the segfault: creating a "normal" context **before** the glutCreateWindow call works and will not segfault.

**Comment by 0nepixel** [comment]
HI SleepProgger, i have a question for you, can you make an example of the code you post in here?, Thanks in advance :)!!
https://godotengine.org/qa/9249/mask-a-sprite-with-a-dynamic-mask
