### ISSUE TITLE
Getting error at Kernel.__init__  while building kernel 

### ISSUE THREAD

**Issue by srijeetaM** [inducer/pyopencl#183]
Hello ,

I am getting this error  when I am trying to build the kernel -

File "/usr/local/lib/python2.7/dist-packages/pyopencl-2015.1-py2.7-linux-x86_64.egg/pyopencl/__init__.py", line 496, in kernel_init
    kernel_old_init(self, prg, name)
Boost.Python.ArgumentError: Python argument types in
    Kernel.__init__(Kernel, _Program, unicode)
did not match C++ signature:
    __init__(_object*, pyopencl::program, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)

I have used gcc version 4.8, python 2.7, opencl 1.2.
Can you please help me with this error.

Thanks,
Srijeeta

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

Looks like the kernel name you're passing is unicode instead of a (byte)string.
