### ISSUE TITLE
Should Array.copy(queue=queue) set the queue of the new array?

### ISSUE THREAD

**Issue by mattwala** [inducer/pyopencl#184]
`Array.copy(queue=new_queue)` currently doesn't set the queue of the returned array to `new_queue`. I found this to be somewhat counterintuitive, but I don't know if it should be considered a bug or not. If it's not a bug, can the documentation be updated?

**Comment by inducer** [comment]
I agree that it's surprising (and likely to lead to incorrect code) that `copy` doesn't also set the queue. Could you MR that change and also clarify the docs for `copy`?

Thx!

**Comment by mattwala** [comment]
Ok. Doing so on gitlab.

**Comment by mattwala** [comment]
Closed by b42e7ebb4364b3cc78a9354e82d3eee7ff67bc32
