### ISSUE TITLE
implement clEnqueueUnmapBuffer

### ISSUE THREAD

**Issue by ernwa** [inducer/pyopencl#185]
Hi, I apologize if this is incorrect, but as far as I know, to operate properly clEnqueueMapBuffer must be matched with clEnqueueUnmapMemObject. I am trying to write zero-copy code and would like to try using mapped buffers, the only usable access to it that I found in the source is in the destructor of memory_map. I feel like it would be much more useful if exposed as a separate function so it could be called as a property of mappings.

**Comment by inducer** [comment]
https://documen.tician.de/pyopencl/runtime_memory.html#mapping-memory-into-host-address-space

`clEnqueueUnmapMemObject` will be called when either
* the `MemoryMap` is deleted,
* `MemoryMap.release()` is called,
* or on context manager exit.

But you're right--this isn't very obvious. I've improved the docs a bit.
