### ISSUE TITLE
array offset units are bytes?

### ISSUE THREAD

**Issue by SyamGadde** [inducer/pyopencl#187]
Hi, in:

https://github.com/pyopencl/pyopencl/blob/5ca953f8cb02d8f6571d0a57fc35b08987f4671f/pyopencl/array.py#L249

it implies that `offset` should be interpreted as in units of the data type, but from the code (particularly `array.Array.__getitem__` and `tools.get_arg_offset_adjuster_code`) it's clear that the units of `offset` is bytes, since it is directly calculated from `strides` which is in bytes.

If this is correct, could you update the documentation?  If it is not correct, can you let me know?  This would affect anyone using array slices via base_data/offset in custom kernels.

Thanks!

**Comment by inducer** [comment]
> strides which is in bytes

Um. `strides` is also in units of the data type. Perhaps I should document that. :)

**Comment by inducer** [comment]
(Or, that'd go more quickly if you could shoot me a PR.)

**Comment by SyamGadde** [comment]
Oh, is that what you intended?  In numpy arrays, strides is in bytes, and `to_device` uses the numpy array's strides as is.  That's why I wanted to make sure with you before proposing a PR.  Numpy has been pretty consistent about using bytes for strides.  See below, offset of the first element in an array of 4-byte elements is 4:

```
In [1]: import pyopencl

In [2]: import pyopencl.array

In [3]: import numpy

In [4]: context = pyopencl.create_some_context()
Choose platform:
[0] <pyopencl.Platform 'AMD Accelerated Parallel Processing' at 0x7f9543ee3430>
Choice [0]:0
Choose device(s):
[0] <pyopencl.Device 'Turks' on 'AMD Accelerated Parallel Processing' at 0x3541fa0>
[1] <pyopencl.Device 'Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz' on 'AMD Accelerated Parallel Processing' at 0x3c96a50>
Choice, comma-separated [0]:1
Set the environment variable PYOPENCL_CTX='0:1' to avoid being asked again.

In [5]: queue = pyopencl.CommandQueue(context)

In [6]: a_g = pyopencl.array.to_device(queue, numpy.arange(10).astype(numpy.float32))

In [7]: a_g[1:].offset
Out[7]: 4

In [8]: a_g.strides
Out[8]: (4,)
```

**Comment by SyamGadde** [comment]
And you already did document `strides` as measured in bytes. :-)

https://documen.tician.de/pyopencl/array.html#pyopencl.array.Array.strides

**Comment by inducer** [comment]
Arf. I got myself confused with how [loopy](https://documen.tician.de/loopy/) does things. It *does* count in units of the data type. But you're right, PyOpenCL is the same as numpy.

Sorry for the confusion, and thanks for bringing this to my attention!
