### ISSUE TITLE
Asyncio support

### ISSUE THREAD

**Issue by iiSeymour** [inducer/pyopencl#188]
I was following this [stackoverflow](https://stackoverflow.com/questions/43550756/setting-asyncio-futures-value-in-a-callback-from-different-thread) question on running pyopencl with Python 3's asyncio framework and ran into some trouble.  

```python
import asyncio
import pyopencl as cl

def wrap_opencl_event(event):
    loop = asyncio.get_event_loop()
    future = loop.create_future()
    cb = lambda status: loop.call_soon_threadsafe(future.set_result, None)
    event.set_callback(pyopencl.command_execution_status.COMPLETE, cb)
    return future

def run(iter, data):
    # enqueue kernel work
    # <omitted>
    # copy results
    cl.enqueue_copy(queue, dest, src)
    return dest

@asyncio.coroutine
def run_async(iter, data):
    # enqueue kernel work
    # <omitted>
    # copy results
    yield from wrap_opencl_event(cl.enqueue_copy(queue, dest, src, is_blocking=False)
    return dest

# sync version 
run(1, x1)
run(2, x2)
run(3, x3)

# async version
loop = asyncio.get_event_loop()
loop.run_until_complete(asyncio.gather(
    run_async(1, x1),
    run_async(2, x2),
    run_async(3, x3),
))
```

The synchronous version runs as expected but the asynchronous version doesn't complete. The callback handler set on the `NannyEvent` is never triggered. Any idea what is going on here? Or more generally are they any examples on using pyopencl with asyncio?

**Comment by inducer** [comment]
What implementation are you using? If you built PyOpenCL from source, you could insert a `printf` into the C-side callback for `clEventSetCallback` to see if it gets called there. If it does, but PyOpenCL doesn't pass on the call, then that's a PyOpenCl bug. If it doesn't get called in the first place, there's little PyOpenCL can do.

**Comment by iiSeymour** [comment]
Turns out the device I was using only supports OpenLC 1.0 so that explains why `clEventSetCallback` never fired. I ended up using the below approach to work around this.

```python
copy_complete = cl.command_execution_status.COMPLETE                                                                                                                                                  
status = cl.event_info.COMMAND_EXECUTION_STATUS
 
@asyncio.coroutine
def run_async(iter, data):  
    # enqueue kernel work
    # <omitted>
    # copy results
    event = cl.enqueue_copy(queue, dest, src, is_blocking=False)                                                                                                                                                                                     
    while event.get_info(status) != copy_complete:
        yield from asyncio.sleep(1e-4)
    return dest
```

**Comment by inducer** [comment]
Thanks for following up!
