### ISSUE TITLE
Error while importing pyopencl

### ISSUE THREAD

**Issue by simon-r** [inducer/pyopencl#189]
I'm using archlinux.
In the current version of pyopencl I I try to import pyopencl I have this error.

I've the same problem on two machine.
Both with nvidia: GeForce GTX 560, and Quadro K2000

```
import pyopencl as cl

The installed version is: 2017.2-1

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-f1779268ba42> in <module>()
----> 1 import pyopencl as cl

/usr/lib/python3.6/site-packages/pyopencl/__init__.py in <module>()
     35 
     36 try:
---> 37     import pyopencl.cffi_cl as _cl
     38 except ImportError:
     39     import os

/usr/lib/python3.6/site-packages/pyopencl/cffi_cl.py in <module>()
     37 from pytools import memoize_method
     38 
---> 39 from pyopencl._cffi import ffi as _ffi
     40 from .compyte.array import f_contiguous_strides, c_contiguous_strides
     41 

ImportError: /usr/lib/python3.6/site-packages/pyopencl/_cffi.abi3.so: symbol clSetKernelArgSVMPointer, version OPENCL_2.0 not defined in file libOpenCL.so.1 with link time reference

```

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

**Comment by gisele-camargo** [comment]
I got an import error after installing nvidia toolkit and cuda, using spyder:

ImportError: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libOpenCL.so.1: version `OPENCL_2.1' not found (required by /usr/lib/python3/dist-packages/pyopencl/_cffi.abi3.so)

Since I have no experience installing these programs. Can anyone help me, please?

**Comment by inducer** [comment]
Please send a message to the mailing list for tech support.

**Comment by gisele-camargo** [comment]
thank you!
