### ISSUE TITLE
create_some_context() raises on IOError

### ISSUE THREAD

**Issue by bmorcos** [inducer/pyopencl#190]
I am working with Python 2.7.12 on Ubuntu 16.04 and I have installed Intel's OpenCL drivers, but not the Intel SDK. Whenever I try `cl.create_some_context()` I get an error. I am **not** entering any value (although it does say choice [0]) , the error is raised immediately:

```
>>> import pyopencl as cl
>>> ctx = cl.create_some_context()
Choose platform:
[0] <pyopencl.Platform 'Intel(R) OpenCL' at 0x13d4850>
[1] <pyopencl.Platform 'Clover' at 0x7f6ee160bae0>
Choice [0]:Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/pyopencl/__init__.py", line 816, in create_some_context
    answer = get_input("Choice [0]:")
  File "/usr/lib/python2.7/dist-packages/pyopencl/__init__.py", line 800, in get_input
    user_input = raw_input(prompt)
IOError: [Errno 9] Bad file descriptor

```

The OpenCL libraries and drivers got installed to `/opt/intel/opencl` ... I'm wondering if this is a path thing?

**Comment by inducer** [comment]
Try calling `raw_input()` (a Python built-in which pyopencl uses). It looks like that's what's not working, which is not really a PyOpenCL issue.

From PyOpenCL's perspective, you could just manually create the context, without the helper, or possibly pass `interactive=False` to `create_some_context()`.

If you have further tech support concerns, please ask on the mailing list.
