### ISSUE TITLE
Unable to get pyopencl working under anaconda python installations.

### ISSUE THREAD

**Issue by proteus-cpi** [inducer/pyopencl#199]
Have been trying to get pyopencl working under Anaconda environments (both 2.7 and 3.6 versions) without much success.

I am running Ubuntu 16.04 on a quad core machine with both Intel OpenCL SDK and INVIDIA CUDA 7.5 installed, and booth working on their own.

Further I install pyopencl with apt (apt install python-opencl and apt install python3-pyopencl) to check if they work on Python 2.7 and Python 3.6 which are default on the 16.04. Apparently they DO work without a problem for a small test script.

However if I install pyopencl under conda (for both 2.7 and 3.6 environments from conda-forge channel), I get the following error :
```
> python demo3.py 
Traceback (most recent call last):
  File "demo3.py", line 8, in <module>
    ctx = cl.create_some_context()
  File "/home/xxxx/miniconda2/envs/PY36/lib/python3.6/site-packages/pyopencl/__init__.py", line 591, in create_some_context
    platforms = get_platforms()
  File "/home/xxxx/miniconda2/envs/PY36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 672, in get_platforms
    _handle_error(_lib.get_platforms(platforms.ptr, platforms.size))
  File "/home/xxxx/miniconda2/envs/PY36/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 645, in _handle_error
    raise e
pyopencl.cffi_cl.LogicError: clGetPlatformIDs failed: <unknown error -1001>
```
The error reported is similar for both Conda installed 2.7 and 3.6 environments. This is even when the apt installed pyopencl continue to work if I deactivate the conda environments.

Looks like I am missing out on small details. ny help appreciated.

[Have tried the same setup on two different machines with same results!]

Regards

script used

```
from __future__ import absolute_import, print_function
import numpy as np
import pyopencl as cl

a_np = np.random.rand(50000).astype(np.float32)
b_np = np.random.rand(50000).astype(np.float32)

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

mf = cl.mem_flags
a_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=a_np)
b_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=b_np)

prg = cl.Program(ctx, """
__kernel void sum(
    __global const float *a_g, __global const float *b_g, __global float *res_g)
{
  int gid = get_global_id(0);
  res_g[gid] = a_g[gid] + b_g[gid];
}
""").build()

res_g = cl.Buffer(ctx, mf.WRITE_ONLY, a_np.nbytes)
prg.sum(queue, a_np.shape, None, a_g, b_g, res_g)

res_np = np.empty_like(a_np)
cl.enqueue_copy(queue, res_np, res_g)

# Check on CPU with Numpy:
print(res_np - (a_np + b_np))
print(np.linalg.norm(res_np - (a_np + b_np)))

```

**Comment by inducer** [comment]
Based on your questions, I've just spent some time writing better installation instructions:

https://documen.tician.de/pyopencl/misc.html#installation

I hope these help you get a working installation of PyOpenCL quickly and easily. If not, please get in touch using the PyOpenCL mailing list for support.

**Comment by proteus-cpi** [comment]
Thanks Andreas. That was quick.
One small correction. In my case, I have installed miniconda at  /home/xxxx/miniconda2/ . But copying the ICDs to "/home/xxxx/miniconda2/etc/OpenCL/vendors/" which already existed did not work!

Instead I had to copy them to  environment specific fiolder (which also existed and contained the pocl.icd ): 
 /home/xxxx/miniconda2/envs/PY36/etc/OpenCL/vendors/

Will post to the mailing list if any other problem arises.
Thanks a bunch.
&
Regards
