### ISSUE TITLE
`enqueue_map_buffer` ignores dtype if it is a record

### ISSUE THREAD

**Issue by bluecube** [inducer/pyopencl#203]
When mapping a buffer with float4 dtype (the same for other record dtypes) in 2017.2, the returned array has a void dtype. This seems to be because `pyopencl.cltypes.float4.str == "|V16"`.

This can be worked around by adding `.view(dtype)` to [before returning the array in `enqueue_map_buffer`](https://github.com/inducer/pyopencl/blob/b73cf47da50d20b78c11d6e40821b83bb8c065cd/pyopencl/cffi_cl.py#L2190). This feels a bit like a kludge though, it would be nicer if the `MemoryMap` was created with the correct dtype in the first place, but I don't understand the internals enough to change this.

**Comment by inducer** [comment]
Could you write a failing test for me? I'll make it succeed.

**Comment by inducer** [comment]
(Or argue that it shouldn't. :)

**Comment by bluecube** [comment]
```
import numpy
import pyopencl
import pyopencl.cltypes

ctx = pyopencl.create_some_context()
queue = pyopencl.CommandQueue(ctx)

def test_map_dtype(dtype):
    dt = numpy.dtype(dtype)

    b = pyopencl.Buffer(ctx,
                        pyopencl.mem_flags.READ_ONLY,
                        dt.itemsize)
    array, ev = pyopencl.enqueue_map_buffer(queue, b, pyopencl.map_flags.WRITE, 0,
                                            (1,), dt)
    with array.base:
        print(array.dtype)
        assert array.dtype == dt

test_map_dtype(pyopencl.cltypes.uint)
test_map_dtype(pyopencl.cltypes.uint2)
```

The first test succeeds, the second fails.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pyopencl/merge_requests/22

**Comment by inducer** [comment]
It's pretty bizarre that just assigning the dtype works, but I guess I'm OK with it. `.view()` actually doesn't work, because then `.base` points at the wrong thing.

At any rate, thanks for the report!

**Comment by inducer** [comment]
CI passed, merged.

**Comment by bluecube** [comment]
Thanks
