### ISSUE TITLE
pyopencl.cffi_cl.RuntimeError: This class cannot be instantiated.

### ISSUE THREAD

**Issue by ghost** [inducer/pyopencl#204]
Dears,

I just installed pyopencl on my machine (Ubuntu 16.04, 64bit, Anaconda 4.4, Intel OpenCL SDK.) and I'm getting this error by using it:

>>> cl.platform_info()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/pyopencl/cffi_cl.py", line 300, in __init__
    raise RuntimeError("This class cannot be instantiated.")
pyopencl.cffi_cl.RuntimeError: This class cannot be instantiated.

can you advice what issue it might be?

Thank you.

Best regards

CLINFO:
(root) ubuntu@ubuntu:~/anaconda3/bin$ clinfo
Number of platforms                               3
  Platform Name                                   Experimental OpenCL 2.1 CPU Only Platform
  Platform Vendor                                 Intel(R) Corporation
  Platform Version                                OpenCL 2.1 LINUX
  Platform Profile                                FULL_PROFILE

 Platform Name                                   Intel(R) OpenCL
Number of devices                                 2
  Device Name                                     Intel(R) HD Graphics
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 
  Driver Version                                  r5.0.63503
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE

  Device Name                                     Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 2.0 (Build 475)
  Driver Version                                  1.2.0.475
  Device OpenCL C Version                         OpenCL C 2.0 
  Device Type                                     CPU
  Device Profile                                  FULL_PROFILE

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

Also, why do you want to instantiate that class? (Answer in a mailing list post, please.)
