### ISSUE TITLE
Documentation: pyopencl.enqueue_fill_buffer: unit for offset and size

### ISSUE THREAD

**Issue by luziferius** [inducer/pyopencl#206]
In my application, i’d like to queue partial buffer fills as part of an algorithm. I found that i should be able to use pyopencl.enqueue_fill_buffer for this task.

The parameter documentation currently says `pattern – a buffer object (likely a numpy.ndarray, eg. np.uint32(0))`. (https://documen.tician.de/pyopencl/runtime_memory.html#pyopencl.enqueue_fill_buffer)
The example explicitly uses a np.uint32, which is 4 bytes long.
But the documentation does not explain if this affects the offset and size parameter.
When I use  `pattern=np.uint32(0), size=1, offset=1`, does it fill 4 bytes (the size of uint32) at byte position 4 (offset 1 in a uint32-array), or does it fill 1 byte at position 1? What happens if size is not a multiple of the pattern size?

The documentation should mention if the parameters size and offset count in bytes or in `sizeof(pattern)`.

**Comment by inducer** [comment]
Thanks for reporting this!
