### ISSUE TITLE
pip install pyopencl fails on 2017.2

### ISSUE THREAD

**Issue by andyofmelbourne** [inducer/pyopencl#210]
I hope this is the right place to report this issue. Basically:
`pip install pyopencl`
fails with:
`src/c_wrapper/clinfo_ext.h:10:19: fatal error: CL/cl.h: No such file or directory`
The full output is attached [bad_pip_install_pyopencl.txt](https://github.com/inducer/pyopencl/files/1480096/bad_pip_install_pyopencl.txt).
System: ubuntu 16.04 LTS
graphics: GeForce GTX 1050 Ti/PCIe/SSE2

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support.

**Comment by andyofmelbourne** [comment]
Ah ok, no problem... the old mailing list eh, very old-school.
