### ISSUE TITLE
terminate called without an active exception

### ISSUE THREAD

**Issue by whbdupree** [inducer/pyopencl#213]
I get this when I run Dr Dobb's sample code( http://www.drdobbs.com/open-source/easy-opencl-with-python/240162614?pgno=2 ). The computation appears to be done correctly. My output is pasted below:

$ python3 drdobbs.py 
[   85.  1360.   147.   285.]
terminate called without an active exception
Aborted

**Comment by whbdupree** [comment]
Maybe this info is helpful:
In [1]: import pyopencl as cl

In [2]: cl.version.VERSION_TEXT
Out[2]: '2016.2'
In [4]: platform = cl.get_platforms()[0]

In [5]: platform = cl.get_platforms()

In [6]: cl.get_platforms()
Out[6]: 
[<pyopencl.Platform 'Clover' at 0x7ff7c6de3040>,
 <pyopencl.Platform 'Portable Computing Language' at 0x7ff7cb7fc020>]

In [7]: platform = cl.get_platforms()[0]

In [8]: platform.get_devices()
Out[8]: [<pyopencl.Device 'AMD PALM (DRM 2.50.0 / 4.13.0-1-amd64, LLVM 5.0.0)' on 'Clover' at 0x11bbf18>]

**Comment by inducer** [comment]
This looks like an issue with Clover rather than PyOpenCL. Please let me know if you can reproduce the issue with an other ICD, e.g. https://github.com/pocl/pocl (which, by the looks of it, you have already installed).

**Comment by inducer** [comment]
In particular, I'd recommend replacing their context creation sequence with

```
ctx = cl.create_some_context()
```

This will allow you to interactively choose what device you'd like to use.

**Comment by cocoa1231** [comment]
I can confirm that this is an issue with clover. 

I'm just starting out so I'm not sure how to go about debugging it. Can someone guide me with that? Thanks
