### ISSUE TITLE
too big max_constant_buffer_size on Intel HD Graphics

### ISSUE THREAD

**Issue by kklmn** [inducer/pyopencl#216]
Hello,

Firstly, thank you for your great tool that we are heavily using in our applications! (xrt.rtfd.io)

I am trying to figure out where originates the segmentation fault that I am getting on Intel HD Graphics 620 (and not on the other two devices in my list). By looking at device.max_constant_buffer_size I get:
- 64 KB on GeForce 940MX
- 2097152 KB (!) on Intel(R) HD Graphics 620
- 128 KB on Intel(R) Core(TM) i7-7500U CPU

Notice the 2nd value is so much different from the other two. Can you please confirm this value originates outside pyopencl?

Thanks!
Konstantin

For reference: OpenCL Platforms and Devices

Platform - Name:  NVIDIA CUDA
------------------------------------
Platform - Vendor:  NVIDIA Corporation
Platform - Version:  OpenCL 1.2 CUDA 9.1.104
Platform - Extensions:  cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_fp64 cl_khr_byte_addressable_store cl_khr_icd cl_khr_gl_sharing cl_nv_compiler_options cl_nv_device_attribute_query cl_nv_pragma_unroll cl_nv_d3d10_sharing cl_khr_d3d10_sharing cl_nv_d3d11_sharing cl_nv_copy_opts cl_nv_create_buffer
Platform - Profile:  FULL_PROFILE
    --------------------------------------------------------
    Device - Name:  GeForce 940MX
    Device - Vendor:  NVIDIA Corporation
    Device - Type:  GPU
    Device - Max Clock Speed:  1241 Mhz
    Device - Compute Units:  3
    Device - Local Memory:  48 KB
    Device - Constant Memory:  64 KB
    Device - Global Memory: 2 GB
    Device - FP:  63

Platform - Name:  Intel(R) OpenCL
------------------------------------
Platform - Vendor:  Intel(R) Corporation
Platform - Version:  OpenCL 2.1 
Platform - Extensions:  cl_intel_dx9_media_sharing cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_d3d11_sharing cl_khr_depth_images cl_khr_dx9_media_sharing cl_khr_fp64 cl_khr_gl_sharing cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_icd cl_khr_image2d_from_buffer cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_spir
Platform - Profile:  FULL_PROFILE
    --------------------------------------------------------
    Device - Name:  Intel(R) HD Graphics 620
    Device - Vendor:  Intel(R) Corporation
    Device - Type:  GPU
    Device - Max Clock Speed:  1050 Mhz
    Device - Compute Units:  24
    Device - Local Memory:  64 KB
    Device - Constant Memory:  2097152 KB
    Device - Global Memory: 6 GB
    Device - FP:  63
    --------------------------------------------------------
    Device - Name:  Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Device - Vendor:  Intel(R) Corporation
    Device - Type:  CPU
    Device - Max Clock Speed:  2700 Mhz
    Device - Compute Units:  4
    Device - Local Memory:  32 KB
    Device - Constant Memory:  128 KB
    Device - Global Memory: 16 GB
    Device - FP:  63

**Comment by kif** [comment]
On Tue, 26 Dec 2017 04:21:28 -0800
Konstantin Klementiev <notifications@github.com> wrote:

> Hello,
> 
> Firstly, thank you for your great tool that we are heavily using in our applications! (xrt.rtfd.io)
> 
> I am trying to figure out where originates the segmentation fault that I am getting on Intel HD Graphics 620 (and not on the other two devices in my list). By looking at device.max_constant_buffer_size I get:
> - 64 KB on GeForce 940MX
> - 2097152 KB (!) on Intel(R) HD Graphics 620
> - 128 KB on Intel(R) Core(TM) i7-7500U CPU
> 
> Notice the 2nd value is so much different from the other two. Can you please confirm this value originates outside pyopencl?

Hi,

I checked on a macbook with a "Intel(R) HD Graphics Haswell Ultrabook GT3 reserved", so the same kind of hardware, just a bit older: 

mac13:~$ clinfo  |grep constant
  Max constant buffer size                        134217728 (128MiB)
  Max number of constant args                     8
  Max constant buffer size                        131072 (128KiB)
  Max number of constant args                     480
  Max constant buffer size                        65536 (64KiB)
  Max number of constant args                     8

The max constant memory reported is 1000x larger than what is claimed by either the intel or AMD driver on CPU. So your results don't surprize me much.

Cheers,
Jerome

**Comment by inducer** [comment]
As @kif said, it's unlikely that this value--correct or not--has anything to do with PyOpenCL. PyOpenCL merely passes it from the implementation to the user code.

Reopen if you have reason to suspect that it is PyOpenCL's fault after all.
