### ISSUE TITLE
RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - 

### ISSUE THREAD

**Issue by assadRasheed** [inducer/pyopencl#221]
### `how to solve above isssue``
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-ebe41d061ca0> in <module>()
     81 
     82 
---> 83 with nengo_ocl.Simulator(model) as sim:
     84     sim.run(n_presentations * presentation_time)
     85 

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in __init__(self, network, dt, seed, model, context, n_prealloc_probes, profiling, if_python_code, planner, progress_bar)
    306         with Timer() as plans_timer:
    307             for op_type, op_list in op_groups:
--> 308                 plans.extend(self.plan_op_group(op_type, op_list))
    309             plans.extend(self.plan_probes())
    310 

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in plan_op_group(self, op_type, ops)
    600 
    601     def plan_op_group(self, op_type, ops):
--> 602         return getattr(self, 'plan_' + op_type.__name__)(ops)
    603 
    604     def plan_PreserveValue(self, ops):  # LEGACY

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in plan_SimProcess(self, all_ops)
    930                 python_ops.extend(ops)
    931 
--> 932         process_plans = [p for attr, ops in iteritems(plan_groups)
    933                          for p in getattr(self, attr)(ops)]
    934         python_plans = [p for op in python_ops

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in <listcomp>(.0)
    931 
    932         process_plans = [p for attr, ops in iteritems(plan_groups)
--> 933                          for p in getattr(self, attr)(ops)]
    934         python_plans = [p for op in python_ops
    935                         for p in self._plan_python_process(op)]

~\Anaconda3.0\lib\site-packages\nengo_ocl\simulator.py in _plan_Conv2d(self, ops)
   1024             plans.append(plan_conv2d(
   1025                 self.queue, X, Y, F, B, p.shape_in, p.shape_out,
-> 1026                 kernel_shape, conv, p.padding, p.strides))
   1027 
   1028         return plans

~\Anaconda3.0\lib\site-packages\nengo_ocl\clra_nonlinearities.py in plan_conv2d(queue, X, Y, filters, biases, shape_in, shape_out, kernel_shape, conv, padding, strides, tag, transposed)
   1642 
   1643     full_args = (X.base_data, filters.data, biases.data, Y.base_data)
-> 1644     _fn = cl.Program(queue.context, text).build().conv2d
   1645     _fn.set_args(*full_args)
   1646 

~\Anaconda3.0\lib\site-packages\pyopencl\__init__.py in build(self, options, devices, cache_dir)
    460                         self._context, self._source, options_bytes, devices,
    461                         cache_dir=cache_dir, include_path=include_path),
--> 462                     options_bytes=options_bytes, source=self._source)
    463 
    464             if was_cached:

~\Anaconda3.0\lib\site-packages\pyopencl\__init__.py in _build_and_catch_errors(self, build_func, options_bytes, source)
    504         # Python 3.2 outputs the whole list of currently active exceptions
    505         # This serves to remove one (redundant) level from that nesting.
--> 506         raise err
    507 
    508     # }}}

RuntimeError: clBuildProgram failed: BUILD_PROGRAM_FAILURE - 

Build on <pyopencl.Device 'Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz' on 'Intel(R) OpenCL' at 0x5f38944>:

Compilation started
:24:11: error: invalid operands to binary expression ('const __global float *' and 'double')
:25:11: error: invalid operands to binary expression ('__global float *' and 'double')
Compilation failed

(options: -I "c:\users\zaid-pc\anaconda3.0\lib\site-packages\pyopencl\cl")
(source saved as C:\Users\zaid-pc\AppData\Local\Temp\tmp2vn8kkek.cl)

```

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
