### ISSUE TITLE
benchmark.py 

### ISSUE THREAD

**Issue by iperov** [inducer/pyopencl#222]
```
data_points = 2**23 # ~8 million data points, ~32 MB data
workers = 2**8 # 256 workers, **play with this to see performance differences**
               # eg: 2**0 => 1 worker will be non-parallel execution on gpu
               # data points must be a multiple of workers
```
srsly ? What the benchmark, if you cannot provide the code to load EVERY THREADS SIMULTANEOUSLY in GPU to measure real performance, and suggest to user to play with workers values ...

**Comment by inducer** [comment]
I agree that this is not worthwhile as a benchmark. SInce I don't have the time to fix it, I've gone ahead and deleted it.

**Comment by iperov** [comment]
bye bye opencl,
cuda ftw
