### ISSUE TITLE
Segmentation Fault after installation

### ISSUE THREAD

**Issue by gijsschot** [inducer/pyopencl#225]
I am trying to install pyopencl on CentOS Linux release 7.3.1611 (Core). 
After running: python setup.py install I have problems importing pyopencl

in python "import pyopencl" gives me the following error:
**Segmentation fault (core dumped)**

I have added '/usr/local/cuda-8.0/include' to the CL_INC_DIR
Any idea why this happens?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Please include a backtrace when you contact the list.
