### ISSUE TITLE
How to access device id in cython

### ISSUE THREAD

**Issue by kodonnell** [inducer/pyopencl#226]
I'm trying to add parameter overrides to CLBlast (see https://github.com/CNugteren/CLBlast/pull/255) and somehow need to pass the `cl_device_id` to the first arguments of `OverrideParameters`. It feels like I should be able to get it from `ctx.devices[0].ptr` or some such, so I tried:

```
 ctypedef void* cl_device_id
...
<cl_device_id> ctx.devices[0].ptr
```
However, I'm getting segfaults. That's might be unrelated, but I suspect it's this.

Hoping this is a one-liner answer - if not, then a feature request.

**Comment by inducer** [comment]
I think you want `int_ptr`, not `ptr`.

**Comment by kodonnell** [comment]
Thanks, sorted. See https://github.com/CNugteren/CLBlast/pull/255#discussion_r173549306 for those interested in the cython stuff.
