### ISSUE TITLE
Program compile example

### ISSUE THREAD

**Issue by mdclemen** [inducer/pyopencl#229]
I've come to pyOpenCL from using pyCUDA. I was a fan of compiling my .cu files to .cubin, and then using the `driver.module_from_file()` function to load the binary file. I have been searching for a way to offline compile my OpenCL kernels in the same fashion and the best analogues I have seen is to use the `.build()` or `.compile()` method of the `pyopencl.Program` class. I have been using the `.build()` method and specifying a directory for the `cache_dir` argument. For example I have modified the [demo.py](https://github.com/inducer/pyopencl/blob/master/examples/demo.py) file to do this with `cache_dir="./"` which creates a directory with three files: binary, info and source.cl. Next I've tried to instantiate the `Program` like so: 
`myplatform = cl.get_platforms()`
`mydev = myplatform[1].get_devices()`
`clbin = [[open("./ebfeee3358458ec6a55d8fe2939349ff/binary", "rb").fileno()]]`
`prg = cl.Program(ctx, mydev, clbin)`
which results in:
`LogicError: clCreateProgramWithBinary failed: INVALID_BINARY`.

I've also tried just doing `prg = cl.Program(ctx, some_kernel_string).compile()` which gives this error:
`AttributeError: 'NoneType' object has no attribute 'compile'`. I've been scouring the web for an example with no luck. Does anyone have an example of how to do this? If someone can show me how, I don't mind writing an example for this repo. Thanks.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

https://github.com/inducer/pyopencl/blob/master/test/test_wrapper.py#L614
