### ISSUE TITLE
Does pyopencl passes build params to compiler?

### ISSUE THREAD

**Issue by vvoznesensky** [inducer/pyopencl#231]
Hello.

I'm trying to use OpenCL 2.0 by passing -cl-std=CL2.0 to program.build(), but it seems that the compiler does not change it's behaviour.

Thank you.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

It is easy to verify that PyOpenCL passes on options by (e.g.) writing code with `#ifdef SOME_MACRO` and passing `["-D", "SOME_MACRO"]` for build options.

**Comment by vvoznesensky** [comment]
Thank you.
