### ISSUE TITLE
Garbage results with AMDGPU-PRO driver and AMD 280X

### ISSUE THREAD

**Issue by rdemaria** [inducer/pyopencl#232]
`python examples/demo.py` returns 
```
[-0.85547698 -0.53161097 -1.26669073 ...,         nan         nan
         nan]
nan
```
or 
```
[ 0.13502347 -0.94461232 -0.60665464 ..., -0.70873618 -0.42645711
 -0.52342105]
157.591
```
when running once more on at 280X using the latest AMDGPU-PRO Driver. The same GPU works well with the fglrx opencl driver.

It is possible that is a driver issues because to run I need to use:
```
export GPU_FORCE_64BIT_PTR=1
```
and the 280X is not officially supported. However other OpenCL codes like clpeak or memtestCL seem to work fine.

Perhaps there is an inconsistency with the pointers since the GPU use 32 bit pointers .

**Comment by inducer** [comment]
Try a C vector add and see if that works. Do `clpeak` or `memtestCL` check any answers?

**Comment by inducer** [comment]
Also, the rocm stack works well for me on a Fiji, if that helps.

**Comment by rdemaria** [comment]
I tried with a standalone program (simple sum) and I am getting inconsistent results (sometimes correct sometimes not). I have to conclude it is the driver... Rocm does not support Tahiti unfortunately...

**Comment by inducer** [comment]
Thanks for checking. Closing here.
