### ISSUE TITLE
pyopencl doesn't work with OpenCL-ICD-Loader 2.2 

### ISSUE THREAD

**Issue by OmegaDoom** [inducer/pyopencl#242]
Hello. Not sure if it's a bug or made on purpose.
Latest intel drivers include opencl.dll 2.2 and it doesn't work with pyopencl-2018.1.1+cl21-cp37-cp37m-win_amd64.whl. Unfortunatelly there is no cl22 binaries on wiki. Is it possible to fix it by building pyopencl from sources? What about plans to support new opencl?

**Comment by inducer** [comment]
> and it doesn't work with

What error message? What system? Why should OpenCL 2.2 be a problem? (CL is backwards compatible throughout.)

**Comment by OmegaDoom** [comment]
Windows 10.
``
Traceback (most recent call last):
  File "D:\Coding\Coding\python\test\opencl\addition\addition.py", line 1, in <module>
    import pyopencl as cl
  File "C:\Python37-64\lib\site-packages\pyopencl\__init__.py", line 37, in <module>
    import pyopencl.cffi_cl as _cl
  File "C:\Python37-64\lib\site-packages\pyopencl\cffi_cl.py", line 39, in <module>
    from pyopencl._cffi import ffi as _ffi
ImportError: DLL load failed: The specified procedure could not be found.
``
opencl.dll 2.1 is working fine.

**Comment by inducer** [comment]
Could you use [dep walker](http://dependencywalker.com/) to figure out what specifically it is not finding?

**Comment by OmegaDoom** [comment]
Yes, in opencl.dll 2.2 functions clCreateProgramWithIL and clEnqueueSVMMigrateMem are missing.

[opencl2.1.dwi.zip](https://github.com/inducer/pyopencl/files/2384146/opencl2.1.dwi.zip)
[opnecl2.2.dwi.zip](https://github.com/inducer/pyopencl/files/2384147/opnecl2.2.dwi.zip)

**Comment by OmegaDoom** [comment]
Looks like broken opencl.dll. I built 2.2 from official repo and it works fine.

**Comment by inducer** [comment]
That was my thought, too. Glad you were able to confirm it.
