### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by OmegaDoom** [inducer/pyopencl#247]
Hi.
I'm building pyopencl with visual studio 2017 cl and have this error.

```
d:\coding\coding\pyopencl\src\wrap_cl.hpp(2068): fatal error C1057: unexpected end of file in macro expansion
```
The problems is here:

```
#if PY_VERSION_HEX >= 0x03020000
        if (PySlice_GetIndicesEx(slc.ptr(),
#else
        if (PySlice_GetIndicesEx(reinterpret_cast<PySliceObject *>(slc.ptr()),
#endif
              my_length, &start, &end, &stride, &length) != 0)
```
PySlice_GetIndicesEx is macro in python 3.7 and looks like it's not allowed in microsoft cl to split macro arguments by macro statements like #else and so on. In gcc it's ok.

**Comment by inducer** [comment]
Thanks for reporting this. How does

https://gitlab.tiker.net/inducer/pyopencl/merge_requests/57

look to you?

**Comment by OmegaDoom** [comment]
Looks good.

**Comment by inducer** [comment]
Thanks! In it goes.
