### ISSUE TITLE
kernel_workgroup_info_error

### ISSUE THREAD

**Issue by tbetcke** [inducer/pyopencl#251]
Hi,

in PyOpenCL 2018.2 I receive the following error when trying to obtain kernel workgroup information:

    def kernel_get_work_group_info(self, param, device):
        try:
>           return self._wg_info_cache[param, device]
E           AttributeError: 'pyopencl._cl.Kernel' object has no attribute '_wg_info_cache'

This does not happen in 2018.1.

Best wishes

Timo

**Comment by inducer** [comment]
Dupe of #244.

**Comment by inducer** [comment]
I'm guessing what you'd like out of me is a release. I guess I can do that, maybe later today sometime.

**Comment by tbetcke** [comment]
Thanks. I overlooked the earlier issue. I downgraded to the 2018.1 version. So I am fine for now.
Best wishes

Timo

**Comment by inducer** [comment]
Released 2018.2.1.

**Comment by tbetcke** [comment]
Installed and all tests are passing now. Thanks
