### ISSUE TITLE
enqueue_copy and default arguments for buffer_pitches/host_pitches

### ISSUE THREAD

**Issue by geggo** [inducer/pyopencl#253]
https://github.com/inducer/pyopencl/blob/1e850da761797c70aa0b2580845585c2401dd0a0/src/wrap_cl_part_1.cpp#L286-L287

Here an sequence is expected, default argument should be py::tuple() instead of py::none()

Gregor

**Comment by geggo** [comment]
Forgot to mention this also applies to lines

https://github.com/inducer/pyopencl/blob/master/src/wrap_cl_part_1.cpp#L298-L299

https://github.com/inducer/pyopencl/blob/1e850da761797c70aa0b2580845585c2401dd0a0/src/wrap_cl_part_1.cpp#L310-L311

**Comment by inducer** [comment]
I agree that this is an issue. The correct fix (since we have to keep accepting `None`) would IMO be to change the argument to a `py::object` type and py::cast<py::seqence>` if it is not `None`. You may also need to add `.none(true)` to the wrapper code. (Examples exist elsewhere in the wrapper code.)

Could you submit a MR at https://gitlab.tiker.net/inducer/pyopencl? I've created a user account for you there.

**Comment by geggo** [comment]
> Am 05.11.2018 um 19:43 schrieb Andreas Klöckner <notifications@github.com>:
> 
> I agree that this is an issue. The correct fix (since we have to keep accepting None) would IMO be to change the argument to a py::object type and py::castpy::seqenceif it is notNone. You may also need to add .none(true)` to the wrapper code. (Examples exist elsewhere in the wrapper code.)
> 
> Could you submit a MR at https://gitlab.tiker.net/inducer/pyopencl? I've created a user account for you there.
> 
Dear Andreas, 
Yes I will try to provide a revised patch tomorrow, might take a while, I am new to pybind11. 
Best
Gregor

**Comment by geggo** [comment]
> Am 05.11.2018 um 21:20 schrieb Gregor Thalhammer <Gregor.Thalhammer@gmail.com>:
> 
> 
> 
> Am 05.11.2018 um 19:43 schrieb Andreas Klöckner <notifications@github.com <mailto:notifications@github.com>>:
> 
>> I agree that this is an issue. The correct fix (since we have to keep accepting None) would IMO be to change the argument to a py::object type and py::castpy::seqenceif it is notNone. You may also need to add .none(true)` to the wrapper code. (Examples exist elsewhere in the wrapper code.)
>> 
>> Could you submit a MR at https://gitlab.tiker.net/inducer/pyopencl <https://gitlab.tiker.net/inducer/pyopencl>? I've created a user account for you there.
>> 
> Dear Andreas, 
> Yes I will try to provide a revised patch tomorrow, might take a while, I am new to pybind11. 
> Best
> Gregor 

Dear Andreas,

submitted a MR as suggested.

Gregor

**Comment by inducer** [comment]
Closed via https://gitlab.tiker.net/inducer/pyopencl/merge_requests/61.
