### ISSUE TITLE
Doc : Ian Johnson's tutorial link is dead

### ISSUE THREAD

**Issue by mamat-rahmat** [inducer/pyopencl#255]
Ian Johnson's PyOpenCL tutorial link (http://enja.org/2011/02/22/adventures-in-pyopencl-part-1-getting-started-with-python/) is dead.

Archived at https://web.archive.org/web/20170907175053/http://enja.org:80/2011/02/22/adventures-in-pyopencl-part-1-getting-started-with-python

**Comment by inducer** [comment]
Thanks!
