### ISSUE TITLE
Use of PyOpenCL

### ISSUE THREAD

**Issue by ghost** [inducer/pyopencl#256]
installed pyopencl on my embedded Linux devices, but when running "demo.py"

```
root:~/PyOpenCL/examples# python demo.py
Choose platform:
[0] <pyopencl.Platform ' OpenCL Platform' at 0xffff94334590>
Choice [0]:0
Choose device(s):
[0] <pyopencl.Device 'OpenCL Device' at 0x1eacd400>
[1] <pyopencl.Device 'OpenCL Device' at 0x1eacd5e8>
Choice, comma-separated [0]:0
Set the environment variable PYOPENCL_CTX='0:0' to avoid being asked again.
Traceback (most recent call last):
  File "demo.py", line 28, in <module>
    cl.enqueue_read_buffer(queue, dest_buf, a_plus_b).wait()
AttributeError: 'module' object has no attribute 'enqueue_read_buffer'

``` 

I wonder what a problem it might be?

Thanks for you advice.

**Comment by kif** [comment]
I guess it is a duplicate of #248

**Comment by inducer** [comment]
Where did you get your version of `demo.py`? The one that ships with PyOpenCL stopped using the deprecated `enqueue_read_buffer` in 2011, since this commit: 0a730d5e5be3df3229ea14c83dd2b6483bca843.

**Comment by ghost** [comment]
Can you point to latest ...
Thanks.

čt 8. 11. 2018 17:42 odesílatel Andreas Klöckner <notifications@github.com>
napsal:
