### ISSUE TITLE
Docs: ImmediateAllocator uses documentation text from different Allocator

### ISSUE THREAD

**Issue by luziferius** [inducer/pyopencl#265]
Issue: The ImmediateAllocator has the same copy&pasted description as DeferredAllocator.
Link: https://documen.tician.de/pyopencl/tools.html#pyopencl.tools.ImmediateAllocator

To quote the ImmediateAllocator documentation:
```
class pyopencl.tools.ImmediateAllocator(queue, mem_flags=pyopencl.mem_flags.READ_WRITE)
  mem_flags takes its values from pyopencl.mem_flags and corresponds to the flags argument of pyopencl.Buffer.
  DeferredAllocator has the same semantics as regular OpenCL buffer allocation, i.e. it
  may promise memory to be available that later on (in any call to a buffer-using CL function).
  New in version 2013.1.
    __call__(size)
      Allocate a pyopencl.Buffer of the given size.
```

Expected: The documentation should tell me that the ImmediateAllocator fails immediately, if memory allocation fails due to OOM conditions.

**Comment by inducer** [comment]
Thanks! https://gitlab.tiker.net/inducer/pyopencl/merge_requests/71
