### ISSUE TITLE
Current wheel builds violate Khronos ICD loader license

### ISSUE THREAD

**Issue by inducer** [inducer/pyopencl#269]
cc @gmagno 

https://github.com/inducer/pyopencl/pull/264#issuecomment-463028414

**Comment by gmagno** [comment]
@inducer thanks for creating the issue.

I guess I will have to come back to this one once I have a bit more time.

**Comment by inducer** [comment]
@gmagno Thanks again for working on this. I'd be happy to merge a version of this that doesn't have license issues. In the meantime, I've removed the Travis build scripts for now.

**Comment by isuruf** [comment]
See https://github.com/inducer/pyopencl/pull/270

**Comment by gmagno** [comment]
> Thanks again for working on this

@inducer no problem :)

> In the meantime, I've removed the Travis build scripts for now.

That makes total sense :+1:

**Comment by inducer** [comment]
See #273 (now merged). Initial build: https://travis-ci.org/inducer/pyopencl/builds/493379557

**Comment by inducer** [comment]
[Wheels](https://pypi.org/project/pyopencl/2018.2.4/#files)! @gmagno, could you check that these do what you'd like them to?

**Comment by inducer** [comment]
Also, thanks to @gmagno and @isuruf for helping to make this happen.

**Comment by isuruf** [comment]
I checked the python 3.6 x86_64 build and it works.

**Comment by inducer** [comment]
Cool, thank you for checking. Closing here. @gmagno, complain if these don't seem to work.

**Comment by gmagno** [comment]
Also  checked 3.5 and works like charm! Woo-hoo!
@inducer, @isuruf kudos to you guys!
