### ISSUE TITLE
pyopencl compilation fails on powerpc64le

### ISSUE THREAD

**Issue by igor-raits** [inducer/pyopencl#280]
```
BUILDSTDERR: In file included from /usr/include/c++/9/ratio:38,
BUILDSTDERR:                  from /usr/include/c++/9/chrono:38,
BUILDSTDERR:                  from /usr/include/c++/9/thread:38,
BUILDSTDERR:                  from src/wrap_cl.hpp:76,
BUILDSTDERR:                  from src/wrap_constants.cpp:27:
BUILDSTDERR: /usr/include/c++/9/type_traits:75:39: error: ‘__vector(4) __bool int’ is not a valid type for a template non-type parameter
BUILDSTDERR:    75 |   typedef integral_constant<bool, true>     true_type;
BUILDSTDERR:       |                                       ^
BUILDSTDERR: /usr/include/c++/9/type_traits:78:40: error: ‘__vector(4) __bool int’ is not a valid type for a template non-type parameter
BUILDSTDERR:    78 |   typedef integral_constant<bool, false>    false_type;
BUILDSTDERR:       |                                        ^
BUILDSTDERR: /usr/include/c++/9/type_traits:81:56: error: ‘__vector(4) __bool int’ is not a valid type for a template non-type parameter
BUILDSTDERR:    81 |     using __bool_constant = integral_constant<bool, __v>;
BUILDSTDERR:       |                                                        ^
BUILDSTDERR: /usr/include/c++/9/type_traits:100:5: error: expected class-name before ‘{’ token
BUILDSTDERR:   100 |     { };
BUILDSTDERR:       |     ^
```

I'm trying to compile latest version of pyopencl for Fedora.

**Comment by inducer** [comment]
Could you see if you can compile the C++ program
```cxx
#include <thread>
```
on your compiler? It looks like that's the bit that's failing, and I'm not sure it has much to do with PyOpenCL. FWIW, I tried building with
```
gcc version 9.0.1 20190305 (experimental) [trunk revision 269387] (Debian 9-20190305-1) 
```
on amd64, and that compiled fine.

**Comment by kif** [comment]
I tested with gcc7 and gcc8 (on Ubuntu 18.04) and got similar error messages (again on PPC64LE).
But with clang it compiles:
CC=clang python setup.py build

Strange ?

**Comment by isuruf** [comment]
Can you provide a preprocessed source?

**Comment by isuruf** [comment]
Related https://github.com/inducer/pyopencl/pull/166
I guess we should check for the `-std=gnu++*` variants before `-std=c++*`.

**Comment by kif** [comment]
I confirm that changing the `-std=c++14`  into `-std=gnu++14` within the `aksetup_helper.py` file addresses the bug. 
As the `-std=c++14` is appended anyway, configuring the CXX option in the `siteconf.py` to  `-std=gnu++14` is not enough.

Overall this is probably a bug in `gcc`.

**Comment by inducer** [comment]
https://gitlab.tiker.net/inducer/pyopencl/merge_requests/84

**Comment by inducer** [comment]
Just merged. I'm closing this, since this should work around your problem. Reopen if it does not.
