### ISSUE TITLE
Rectangular pyopencl.enqueue_copy 

### ISSUE THREAD

**Issue by pierrepaleo** [inducer/pyopencl#281]
Cuda has a [Memcpy2D](http://developer.download.nvidia.com/compute/cuda/2_3/toolkit/docs/online/group__CUDART__MEMORY_g17f3a55e8c9aef5f90b67cdf22851375.html) function for rectangular copies which works out of the box in `pycuda.gpuarray` (it behaves like numpy arrays).

The OpenCL counterpart is, I believe, [clEnqueueCopyBufferRect](https://www.khronos.org/registry/OpenCL/sdk/1.2/docs/man/xhtml/clEnqueueCopyBufferRect.html).
This function seems to be wrapped by `pyopencl.enqueue_copy()` (for example `pyopencl._cl._enqueue_copy_buffer_rect`).
However, for some reason I cannot make it work with Buffer <-> Buffer and Host <-> Buffer rectangular copies (Image <-> Buffer and Image <-> Host are working).

```python
import pyopencl as cl
import pyopencl.array as parray
ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

arr1 = parray.zeros(queue, (2, 3), "f")
arr2 = parray.zeros(queue, (4, 5), "f")
arr1.fill(1)
# Not implemented
arr2[1:-1, 1:-1] = arr1[:]
# Fails
cl.enqueue_copy(queue, arr2.data, arr1.data, src_origin=(0, 0), dst_origin=(1, 1), region=arr1.shape[::-1])
```

Did I miss something ?

**Comment by inducer** [comment]
Thanks for the report!
