### ISSUE TITLE
clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by MingBit** [inducer/pyopencl#283]
hallo,

well, this might be an old issue. 
I've tried the most frequently mentioned solution: `cp /etc/OpenCL/vendors/*.icd /etc/OpenCL/vendors/`.. unfortunately it didn't work. I have pyopencl and pycuda properly installed.
And I have **nvidia.icd** and **pocl.icd** in both folders afterwards.

The error message shown below:
`
>>> import pyopencl as cl
>>> cl.create_some_context()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/angela/miniconda3/lib/python3.6/site-packages/pyopencl/__init__.py", line 1385, in create_some_context
    platforms = get_platforms()
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR
>>>
Any ideas? many thanks...

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
 
My guess is that your OpenCL drivers (the ICDs) aren't properly installed. Try installing/running `clinfo` and see if anything is listed.

**Comment by MingBit** [comment]
Thanks for the quick response. well, got an (info) issue about "NULL platform behavior" afterwards.
Anyway, I'll send an email to tech support. :)
