### ISSUE TITLE
Segmentation fault on cl.create_some_context()

### ISSUE THREAD

**Issue by omertzuk** [inducer/pyopencl#285]
I am trying to install pyopencl on Ubuntu 16.04. I have tried to use on of the scripts to test the installation, but when I make `cl.create_some_context()` it exit in Segmentation fault.

What could be the problem?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
