### ISSUE TITLE
Looking for '_source' kernel

### ISSUE THREAD

**Issue by AShivangi-zz** [inducer/pyopencl#292]
I wrote a simple hello world pyocl testcase for a Xilinx accelerator card, but I am getting kernel '_source' not found error. I stepped through the code and it seems like the pyopencl code is trying to create a '_source' kernel. Any ideas on how I can work around this?

![image](https://user-images.githubusercontent.com/17800752/61414243-5a05ab00-a8a2-11e9-824d-5c1976d141bc.png)

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

It's hard to help with this without seeing a minimum working example, so I would encourage you to provide this when you contact the mailing list. (I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
