### ISSUE TITLE
Segmentation fault when using two OpenCL libraries

### ISSUE THREAD

**Issue by jmaye** [inducer/pyopencl#293]
Python 3.6.8

pip install pyopencl==2019.1.1
pip install open3d-python==0.7.0.0
pip install ipython==7.7.0

ipython
import open3d
import pyopencl
Segmentation fault (core dumped)

Note that the bug has been introduced in release 2019.1. Before, everything was working fine.

**Comment by isuruf** [comment]
Can you remove pyopencl and do `pip install pyopencl --no-binary`?

**Comment by jmaye** [comment]
I tried it, looks complicated. Stumble on that: version `OPENCL_2.1' not found

I'm using Nvidia, I guess it must be 1.2

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

* It's true that Nvidia only supports CL 1.2, but you can have a CL 2.1 *loader* with a *1.2* driver. So you need to upgrade your ICD loader.
* Your CL headers likely don't match your (likely Nvidia-installed) libOpenCL.so. It's likely that these two came from two different sources. Maybe install https://github.com/KhronosGroup/OpenCL-ICD-Loader.

(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)

**Comment by jmaye** [comment]
I have a hard way understanding your reasoning. The previous version was working perfectly on my machine and the new version not. To me, it's a bug that was introduced in the new version and I'm just pointing it to you if you are interested. Because if I use it standalone all is fine, just when importing two GPU libraries that it fails.

I don't need any technical support and I will never need. I never report bugs like that, but here it felt like you are doing a good job and I wanted to help you, kind of disappointed by your reaction.

On my side, I'll go on with the previous working version, perfectly fine, waiting that the bug gets fixed or not.

Nevertheless thanks for your contribution.

**Comment by jmaye** [comment]
The bug has been solved in version 2019.1.2! Thanks for doing that and next time maybe stop bashing people who report bugs to your library.
