### ISSUE TITLE
how to select intel GPU in pyopencl

### ISSUE THREAD

**Issue by subshall** [inducer/pyopencl#295]
Hello, my GPU is integrated graphics, intel HD 515
My CPU is Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz

I am using clinfo, the output　ｉｓ　

Platform Name Intel(R) OpenCL
Number of devices 2
Device Name Intel(R) Gen9 HD Graphics NEO
Device Vendor Intel(R) Corporation
Device Vendor ID 0x8086
Device Version OpenCL 2.1 NEO
Driver Version 18.28.11080
Device OpenCL C Version OpenCL C 2.0
Device Type GPU
Device Profile FULL_PROFILE
Max compute units 24
Max clock frequency 850MHz
Device Partition (core)
Max number of sub-devices 0
Supported partition types None
Max work item dimensions 3
Max work item sizes 256x256x256

But when I print the device with pyopencl, I get the following result
<pyopencl.Device 'Intel(R) Core(TM) m3-6Y30 CPU @ 0.90GHz' on 'Intel(R) CPU Runtime for OpenCL(TM) Applications' at 0x1a4b0c8> image support: 1

only CPU

I want to know how to select GPU in pyopencl
thanks

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

In addition, please don't spam your nonsense in [all sorts of places](https://github.com/inducer/pyopencl/issues/288#issuecomment-526927618). That's just rude.
