### ISSUE TITLE
crash: pybind11_object_dealloc(): Tried to deallocate unregistered instance

### ISSUE THREAD

**Issue by sinsemellan** [inducer/pyopencl#296]
crash: pybind11_object_dealloc(): Tried to deallocate unregistered instance

We probably hit the same bug as described here [mailing list](https://pyopencl.tiker.narkive.com/j1cd2oRO/crash-pybind11-object-dealloc-tried-to-deallocate-unregistered-instance). We use pyopencl.array.Array.get() on many (about 20) arrays and get random crashes. Executing gc.collect() from a different thread triggers the error reliably. The following example is just a modification from here [original code](https://gist.github.com/geggo/d9b4016ff5b77dab262be7b30a98d862).

We are using python 3.7, latest pyopencl (2019.1.1)
The error occurs on both tested platforms Windows 10 and Ubuntu 18.04.2 LTS, both 64 bit.
The opencl device does not matter, the error occurs on nvidea devices, intel cpu and pocl.

```python
import faulthandler
import gc
import sys
import threading
import time

import numpy as np
import pyopencl as cl
import pyopencl.array as cla

faulthandler.enable()

def create_arrays_thread(n1=10, n2=100, name=""):
  ctx = cl.create_some_context(answers=['0'])
  queue = cl.CommandQueue(ctx)
  for i1 in range(n2):
    for i in range(n1):
      acl = cla.zeros(queue, 10, dtype=np.float32)
      a = acl.get()

def garbage_collect():
  for i1 in range(100):
    # Garbage collection triggers the error
    print("collected ", str(gc.collect()))
    print("stats ", gc.get_stats())
  time.sleep(0.5)

T1 = threading.Thread(target=create_arrays_thread, args=(20, 1000, 'thread 1'))
T2 = threading.Thread(target=garbage_collect)

T1.start()
T2.start()

T1.join()
T2.join()
```

**Comment by inducer** [comment]
Thanks for coming up with this nice, self-contained reproducer. I can reproduce the crash on my end, and I'll take a look.

cc @geggo

**Comment by inducer** [comment]
I made some progress I think. https://gitlab.tiker.net/inducer/pyopencl/merge_requests/92/diffs

**Comment by inducer** [comment]
Let me know if this does not address the issue for you.

**Comment by geggo** [comment]
I can confirm this fixes the deallocation crashes, tested on Python 3.6, macOS, Thanks so much!
