### ISSUE TITLE
[Question] Connecting PyOpenCL to OpenCL called in SWiG.

### ISSUE THREAD

**Issue by Sipondo** [inducer/pyopencl#297]
Hey,
I am working on an extension of a Python package developed by my professor. His package is accelerated via OpenCL using SWiG. I am using this package for my project and am using PyOpenCL for some of my own operations.
We were wondering if it would be possible to set up PyOpenCL / the package in such a way that we can minimise the data transfers between host and device. At the moment, we have to fetch all the data resulting from the PyOpenCL part of the program and to subsequently pass it as arguments to the package. The package then transfers the data back to the GPU (under its own initialisation/command queue).
If of any help, I can supply an example of the problem. Please let me know.

Thank you for your time.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

* Look at the `int_ptr`, `from_int_ptr` static methods in each class.
(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)

**Comment by Sipondo** [comment]
I'm sorry for posting my question under the issue tracker. I was not aware that it was not permitted to post questions here, as it is often permitted. I will redirect further enquiries to the mailing list.
