### ISSUE TITLE
Can it load OpenCL Binary Image Format 2.0 ?

### ISSUE THREAD

**Issue by KOLANICH** [inducer/pyopencl#299]
https://rocm-documentation.readthedocs.io/en/latest/Programming_Guides/Opencl-programming-guide.html#opencl-binary-image-format-bif-v2-0

**Comment by inducer** [comment]
Sure. PyOpenCL exposes (by way of the `Program` constructor the CL API `clCreateProgramFromBinary`, and it directly passes through the byte string it is given. As such, PyOpenCL should work independently of which binary format device vendors decide to use.
