### ISSUE TITLE
Getting clinfo_ext.h: No such file or directory error  

### ISSUE THREAD

**Issue by JKOK005** [inducer/pyopencl#309]
Hi @inducer 

I'm trying to set PyOpenCL up to work with `de5net_a7 : Terasic's Preferred Board. Intel(R) FPGA SDK`

It seems that by default, the FPGA device cannot be picked up by the call to get_platform(). Following the article posted by @nachiket [[link](https://paper.dropbox.com/doc/PyOpenCL-with-Altera-FPGAs-8ojfCVUBhiz7UOjRTIaFe)], I downloaded the tar release from [here](https://pypi.org/project/pyopencl/#files) and modified both siteconf.py and setup.py files to point  to the respective FPGA libraries on my system. 

On the call to do a python installation from setup.py, I get the error:

`
In file included from src/wrap_cl.hpp:58:0,
                     from src/wrap_constants.cpp:30:
    src/pyopencl_ext.h:6:24: fatal error: clinfo_ext.h: No such file or directory
     #include "clinfo_ext.h"
` which is crashing the installation.

Would appreciate some assistance to this matter and how I can properly get PyOpenCL to work for the de5net FPGA. Seems like the standard pip installation is unable to discover the FPGA device automatically.

Thanks!

**Comment by yxliang01** [comment]
@JKOK005 
I have the following questions:
1. Did the package you downloaded install successfully before your modification?
2. What are the concrete modifications you have done? Potentially, paste a file diff here?

**Comment by inducer** [comment]
Thanks for the report! In 4639998, I've added back `clinfo_ext.h`, which accidentally got deleted in the switch from cffi to pybind11 (49ab696f914b6ffa205c077a6484882514733237).

Please reopen if your issue is not solved.

**Comment by yxliang01** [comment]
@inducer Do you mind either publish version 2019.1.2 or confirm with us whether the current master is stable enough to be used?

**Comment by inducer** [comment]
It would be helpful if you could confirm that this does what you would like.

**Comment by JKOK005** [comment]
@inducer thanks for the commit. 

Can confirm that PyOpenCL works with the FPGA on my system. 

However, what I did was to download the zip from https://pypi.org/project/pyopencl/#files, unzipped and added the latest clinfo_ext.h to the directory to get it to work. 

Can you update the release in https://pypi.org/project/pyopencl/#files? The standard pip installation does not pick up FPGAs automatically and I had to modify the setup.py & siteconf.py, as advised by @nachiket's article. Also, installing straight from the master branch has been blocked. 

Moving forward, do you have plans to support the automatic discovery of other external devices (such as FPGAs?)

**Comment by inducer** [comment]
>  do you have plans to support the automatic discovery of other external devices (such as FPGAs?)

Since I don't have a device of that type to test with, I'm unlikely to be able to work on that. I'm happy to consider pull requests that might add such functionality.

**Comment by inducer** [comment]
I've just released 2019.1.2 to the package index. Please let me know if that works for you.

**Comment by yxliang01** [comment]
I feel the support of other devices can be added to pyopencl. Just that mark as "potentially unusable" since none of the contributors looks like using pyopencl for FPGAs.
