### ISSUE TITLE
Debugging error when calling kernel function

### ISSUE THREAD

**Issue by JKOK005** [inducer/pyopencl#314]
@inducer would appreciate some guidance here

I ran a pyopencl code that calls a precompiled kernel binary file. Currently, we are running into a runtime error of `RuntimeError: Unable to compute length of object` (snapshot attached)

We are not sure what the exact cause of the issue is (whether its an issue with pyopencl or the kernel on our end)

Also, is there a way to make the error more verbose, as it is difficult to pinpoint the exact cause from the stack trace? Thanks!

<img width="1340" alt="Screen Shot 2019-11-10 at 9 37 15 PM" src="https://user-images.githubusercontent.com/14960222/68544874-532b1700-0402-11ea-8054-b0455b0eb1b9.png">

**Comment by yxliang01** [comment]
So comes out that this was caused by arguments of wrong data type (multidimensional numpy array). However, we feel that pyopencl can make the error message more concrete to facilitate debugging to make this library more error-friendly :)

**Comment by inducer** [comment]
Thanks for the suggestion. Unfortunately, this is harder than it sounds, as sometimes numpy arrays are perfectly valid kernel arguments. And it's nearly impossible for PyOpenCL to tell which case it is dealing with.

FWIW, if I pass a numpy array where there isn't one expected, I get this:
```
pyopencl._cl.LogicError: when processing argument #1 (1-based): clSetKernelArg failed: INVALID_ARG_SIZE
```

**Comment by yxliang01** [comment]
@inducer This error message we also encountered before when we passed python native object (`int`) and it's indeed good enough. We get this `unable to compute length of object` object when we passed the 2D-array of struct.
