### ISSUE TITLE
Enforce the use of OpenCl 1.2 via pyopenCL

### ISSUE THREAD

**Issue by mwibral** [inducer/pyopencl#315]
My apologies, if this is not the right place to post this question.

We have pyopencl / opencl code that used to run fine, and is still running fine, on devices offering opencl1.2 (nvidia cards, older amd) but has mysterious crashes (possibly when writing back to host memory) when the device in question offers opencl 2.0 capabilities - at least that is the only consistent change we have observed. 

Is there some way to enforce the use of opencl 1.2. from the pyopencl API?

Thanks.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.
