### ISSUE TITLE
Error <module 'pyopencl._cl' has no attribute '_enqueue_fill_buffer'> with intel FPGA device

### ISSUE THREAD

**Issue by dieruiqu** [inducer/pyopencl#319]
Hi, i'm tryin to use ```pyopencl.enqueue_fill_buffer``` from pyopencl with the @nachiket installation for FPGA devices:

https://paper.dropbox.com/doc/PyOpenCL-with-Altera-FPGAs-8ojfCVUBhiz7UOjRTIaFe 

I've been installed 1.1 and 1.2 OpenCL versión how mentions in the oficial documentation with the follow ```siteconfig.py``` file:

```
CL_TRACE = False
CL_ENABLE_GL = False
CL_USE_SHIPPED_EXT = False
CL_PRETEND_VERSION = '1.2'
CL_INC_DIR = ['/root/intelFPGA/17.1/hld/host/include']
CL_LIB_DIR = ['/root/intelFPGA/17.1/hld/board/c5p/linux64/lib',
	      '/root/intelFPGA/17.1/hld/host/linux64/lib',
	      '/root/intelFPGA/17.1/hld/board/custom_platform_toolkit/migration/ref_design/linux64/lib']
CL_LIBNAME = ['terasic_c5p_mmd', 'OpenCL', 'alteracl', 'alterahalmmd','altera_apb_14_0_mmd']
CXXFLAGS = ['-fvisibility=hidden']
LDFLAGS = ['-Wl,--no-as-needed', 
   	   '-Wl,--rpath,/root/intelFPGA/17.1/hld/board/c5p/linux64/lib', 
	   '-Wl,--rpath,/root/intelFPGA/17.1/hld/host/linux64/lib', 
	   '-Wl,--rpath,/root/intelFPGA/17.1/hld/board/custom_platform_toolkit/migration/ref_design/linux64/lib']
```
All works correctly except when i try to use:

```
d_a_buf = cl.enqueue_fill_buffer(globals.QUEUE, 
                                 globals.D_A_BUF[((globals.DIMS[0],globals.DIMS[0]))], 
                                 h_a, 0, globals.A_SIZE)
```

that reports the next error:

```
  File "/root/anaconda3/envs/opencl_fpga_12/lib/python3.7/site-packages/pyopencl-2019.1.2-py3.7-linux-x86_64.egg/pyopencl/__init__.py", line 1860, in enqueue_fill_buffer
    return _cl._enqueue_fill_buffer(queue, mem, pattern, offset, size, wait_for)

AttributeError: module 'pyopencl._cl' has no attribute '_enqueue_fill_buffer'
```

Autocomplete of Spyder IDE recognizes the function and args. Maybe is the OpenCL version of Intel SDK? In docu says that need have installed OpenCL 1.1

Thanks.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

Did you include
```
CL_PRETEND_VERSION = '1.1'
```
in `siteconf.py` when building PyOpenCL?
(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
