### ISSUE TITLE
pyopencl.Buffer freeze when reprogram FPGA via os.popen

### ISSUE THREAD

**Issue by dieruiqu** [inducer/pyopencl#320]
Hi. ``` pyopencl.Buffer() ``` freeze after reprogram the FPGA via ```os.popen()``` only if previously don't restart the kernel. I save and reutilize pyopencl variables and later use its with the follow code :
```
globals.PLATFORMS = cl.get_platforms()
globals.DEVICES   = globals.PLATFORMS[0].get_devices()
globals.CTX       = cl.Context(globals.DEVICES)
globals.BINARY    = open(globals.FILE_NAME, 'rb').read()
globals.PRG       = cl.Program(globals.CTX, globals.DEVICES, [globals.BINARY]).build()
# globals.KERNEL    = set_prg_kernel()
globals.KERNEL    = globals.PRG.all_kernels()[0]
globals.QUEUE     = cl.CommandQueue(globals.CTX, properties=cl.command_queue_properties.PROFILING_ENABLE)
```
Repgroam fpga via ```os.popen()```:

```
def reprogram_kernel():
    try:
        import os
        reprogram_cmd = globals.reprogram + 'acl0' + ' ' + globals.FILE_NAME
        os.popen(reprogram_cmd).read()
        return True
    except:
        return False
```

To set the buffers of A and B:
```
d_a_buf = cl.Buffer(globals.CTX, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=h_a)
d_b_buf = cl.Buffer(globals.CTX, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=h_b)
```

It's here where the program freezes. Before reprogram FPGA generate newly the pyopencl vars, context, program, kernel... etc. and later reprogram FPGA.  Finally, create again the buffers. I've stayed looking for a zombie procces related with intel, altera or spyder and find one Intel zombie process that i  can't  kill, only can kill parent process, that it's kernel, to works again.

Thanks!

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.) You could use `strace` to see what system call hangs the program.
