### ISSUE TITLE
Handing multiple DDR banks when using Xilinx FPGAs?

### ISSUE THREAD

**Issue by Felkin1** [inducer/pyopencl#321]
I can't seem to find in the documentation or the source code any means of selecting the DDR bank to use when creating Buffer objects. 

Xilinx provides an extension that allows this sort of call:

``` cl_mem_ext_ptr_t inExt, outExt;  // Declaring two extensions for both buffers
inExt.flags  = XCL_MEM_DDR_BANK0; // Specify Bank0 Memory for input memory
outExt.flags = XCL_MEM_DDR_BANK1; // Specify Bank1 Memory for output Memory
inExt.obj = source_in.data()   ; 
outExt.obj = source_fpga_results.data(); // Setting Obj and Param to Zero
inExt.param = 0 ; outExt.param = 0;

cl::Buffer buffer_in(
context,CL_MEM_USE_HOST_PTR | CL_MEM_READ_ONLY | CL_MEM_EXT_PTR_XILINX,
                in_matrix_size_bytes,&inExt);
cl::Buffer buffer_output(
context,CL_MEM_USE_HOST_PTR | CL_MEM_WRITE_ONLY | CL_MEM_EXT_PTR_XILINX,
                out_matrix_size_bytes,&outExt);
```

Is there any means of achieving similar functionality? If not, this would be a vital addition to pyopencl for FPGA use.

**Comment by inducer** [comment]
This is already achievable with the current interface. Simply use Python's built-in `struct` module (or something similar) to pack a `bytes` object corresponding to a [`cl_mem_ext_ptr_t`](https://github.com/Xilinx/XRT/blob/b3e04d4d7b215034b9763523f3005977640c2abc/src/include/1_2/CL/cl_ext_xilinx.h#L86) struct, and pass that, along with the required flag, to the `cl.Buffer` constructor.
