### ISSUE TITLE
pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR

### ISSUE THREAD

**Issue by S130111** [inducer/pyopencl#329]
why?

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

(I provide this advice as a courtesy. If you need to follow up, please use the mailing list.)
