### ISSUE TITLE
Potential memory leak with device maps

### ISSUE THREAD

**Issue by tbetcke** [inducer/pyopencl#332]
Hi,

I have been observing memory leaks in my code when allocating larger buffers on a CPU device (POCL driver) and transferring data to them.  A gist demonstrating the memory leak is available at:

https://gist.github.com/tbetcke/9eee76460d71411a8091d3e06b2832e1

On my machine there is around 180MB of memory that is not being released after the loop. This is creating significant problems in one of our applications, where we have a number of buffers being created in each loop iteration, creating gigabytes of leaked memory.

A few observations:

- The leak is most pronounced with POCL (recent version)
- In the presented gist I cannot observe the leak with the Intel CPU driver. However, memory leaks also occur (but could not produce a simple example)
- The AMD Rocm driver also produces leaks, but much smaller than POCL.

This may not necessarily be an issue with PyOpenCL. However, I am not certain how to investigate this further.

**Comment by tbetcke** [comment]
Just another remark. This seems different to issue #300 . There, memory leaks were produced through kernel compilation. Here, they are produced from memory transfers.

**Comment by tbetcke** [comment]
I have now written a C++ code that reproduces the issue and sent a bug report to the Pocl Team. The bug report can be found at: https://github.com/pocl/pocl/issues/812

**Comment by inducer** [comment]
Thanks for following up and tracking down the issue! Sorry I've not been super responsive; I'm crazy busy at the moment, but things are looking up (I hope) as the semester draws to a close.
