### ISSUE TITLE
enqueue_map_buffer() failing w/ type error on buffer argument

### ISSUE THREAD

**Issue by tarfeef101** [inducer/pyopencl#333]
I'm trying to use the enqueue_map_buffer() function in my code, but I'm getting a type error. Specifically:
```
TypeError: enqueue_map_buffer(): incompatible function arguments. The following argument types are supported:
    1. (queue: pyopencl._cl.CommandQueue, buf: pyopencl._cl.MemoryObjectHolder, flags: int, offset: int, shape: object, dtype: object, order: object = 'C', strides: object = None, wait_for: object = None, is_blocking: bool = True) -> object

Invoked with: <pyopencl._cl.CommandQueue object at 0x7f92f4574f68>, <pyopencl._cl.Buffer object at 0x7f92f459e0a0>; kwargs: flags=2, shape=(500000000,)
```

The docs say the buf parameter is a buffer. the concept implies it should be a buffer, and even examples I've seen online involve using it as a buffer. Analogous example code I'm building from in C from nvidia passes in a buffer. Yet this is failing. The only guess I have as to why is this snippet of code from `test/test_wrapper.py`:
```
if cl._PYPY:
--
1058 | # FIXME
1059 | pytest.xfail("enqueue_map_buffer not yet working on pypy")
```

Is this a typo, and does `enqueue_map_buffer()` not work if you use pypi? I am using cpython, so if that really does mean pypy, I'm at a total loss. 

## System info:
Tested on an intel iGPU (kaby lake), and an rtx 2070, using open-source intel and closed-source nvidia drivers.

Package version: 2019.1.2

## Source Code
```
import pyopencl as cl
import numpy as np
import time

a_in = np.random.rand(500000000).astype(np.float32)

ctx = cl.create_some_context(False)
queue =  cl.CommandQueue(ctx)

# mf is a set of constants
mf = cl.mem_flags

# used for calculation of bandwidth
gigs = a_in.nbytes / (2 ** 30)

# create host-side pinned buffers
pinned_in = cl.Buffer(ctx, mf.READ_ONLY | mf.ALLOC_HOST_PTR, size=a_in.nbytes)
pinned_out = cl.Buffer(ctx, mf.WRITE_ONLY | mf.ALLOC_HOST_PTR, size=a_in.nbytes)

# create device buffers
dev_in = cl.Buffer(ctx, mf.READ_ONLY, size=a_in.nbytes)
dev_out = cl.Buffer(ctx, mf.WRITE_ONLY, size=a_in.nbytes)

# map host-side normal vars to pinned memory
host_in, _ = cl.enqueue_map_buffer(queue, pinned_in, flags=cl.map_flags.WRITE, shape=a_in.shape)
```

**Comment by inducer** [comment]
The `dtype` argument is also required. (Since `enqueue_map_buffer` will return a numpy array.)

**Comment by tarfeef101** [comment]
Unfortunately, that is not the issue. Adding `dtype=np.float32` does not solve the issue. As the docs point out, the params work like `np.empty()`, which has a default for dtype (although to be fair it is 64-bit, IIRC). 

The `TypeError` indicates a type mismatch, not a missing param. I believe it is the conflict between the expected `buf: pyopencl._cl.MemoryObjectHolder`, whereas my code provides a `pyopencl._cl.Buffer` (which is what I have seen people passing in examples I've found, as well as the docs which say this param is a buffer).

**Comment by tarfeef101** [comment]
@inducer tagging so you can see this, since the issue was closed before resolution was verified, and since I didn't close, I cannot reopen this (but also don't want to spam duplicate issues).

**Comment by inducer** [comment]
Check [this sample usage](https://github.com/inducer/pyopencl/blob/bb5d8b042225257676b222191f886dabd8b4217e/test/test_wrapper.py#L1069) in the tests.

**Comment by tarfeef101** [comment]
@inducer what about it? It passes in a buffer. Just like I am. Except my error is saying the function expects a different type. Can you address why this is the case?

**Comment by tarfeef101** [comment]
Also if you could please leave the issue open until it is actually resolved, that'd be great. Even if you do continue to follow this thread, other users who may have insight are less likely to see it when it is closed.
