### ISSUE TITLE
async support for array.zeros

### ISSUE THREAD

**Issue by yxliang01** [inducer/pyopencl#343]
`array.zeros` should support async as well.

**Comment by inducer** [comment]
I'm not sure I understand. It does the allocation and enqueues the zero fill. It returns without synchronizing to wait for the zero-fill to complete.

**Comment by yxliang01** [comment]
I'm not too familiar with this codebase. @inducer so you meant that `array.zeros` can only be async? If that's the case, maybe should mention in documentation I think.

**Comment by inducer** [comment]
Thanks for the suggestion, but I think that's understood. OpenCL has very few things that happen synchronously, so it would be surprising (to me) if it was synchronous (rather than the other way around).
