### ISSUE TITLE
Installing on Windows with Intel's SDK using pip

### ISSUE THREAD

**Issue by Foadsf** [inducer/pyopencl#344]
Following [this SO post](https://stackoverflow.com/q/62179484/4999991), I want to install PyOpenCL on Windows having the Intel's OpenCL™ SDK and using `pip`.  I would appreciate if you could provide a step by step instruction for a novice like me. I would appreciate it if we could avoid any compilation or other manual setups.

**Comment by inducer** [comment]
I don't have a Windows machine available, so it's hard for me to even test these instructions. There are [instructions on the Wiki](https://wiki.tiker.net/PyOpenCL/Installation/Windows) however, which may prove useful. As to your question on `siteconf.py`: `configure.py` will write that for you.

In general, I would like to recommend that you send further support requests to the mailing list.

**Comment by Foadsf** [comment]
I have summarized the installation steps [here](https://stackoverflow.com/a/62193875/4999991)

**Comment by inducer** [comment]
Thanks for providing this summary!

**Comment by Foadsf** [comment]
@inducer I just created [a channel](https://discord.gg/88jDDkG) for `#opencl` on Modelica Discord sever. It would be great to have the PyOpenCL community over there as well. If you want we can connect the webhooks to this repo too so people get real-time notifications.
