### ISSUE TITLE
[docs] Add dependency for numpy

### ISSUE THREAD

**Issue by shazz** [inducer/pyopencl#352]
Hi,

I'm using pyopencl on the Raspberry Pi 3 and [VC4CL](https://github.com/doe300/VC4CL) and to install pyopencl using pip3 (python3.7) on Raspbian, I needed to add `sudo apt-get install libatlas-base-dev`

Else I got this error: `Original error was: libf77blas.so.3: cannot open shared object file: No such file or director` with numpy.

Then it worked perfectly (or it looks like) :)

````bash
sudo python3 demo.py
Choose platform:
[0] <pyopencl.Platform 'OpenCL for the Raspberry Pi VideoCore IV GPU' at 0xe43b4c>
Choice [0]:0
Set the environment variable PYOPENCL_CTX='0' to avoid being asked again.
[ 0.0000000e+00  0.0000000e+00 -1.1920929e-07 ...  0.0000000e+00
 -1.4901161e-08  0.0000000e+00]
1.1867789e-05
````

**Comment by inducer** [comment]
Thanks for the report. My read on this is that the way you use to install numpy (how?) left you with a broken numpy install, so it sounds like something that should be fixed upstream (with numpy, not pyopencl).

**Comment by shazz** [comment]
You're welcome!
In fact, I started from a blank python 3.7 environment, I just called `pip3 install pyopencl`, it installed numpy as it is a dependency.

````
pip install pyopencl
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting pyopencl
  Downloading pyopencl-2020.2.tar.gz (351 kB)
     |████████████████████████████████| 351 kB 1.9 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting pytools>=2017.6
  Downloading https://www.piwheels.org/simple/pytools/pytools-2020.3.1-py2.py3-none-any.whl (65 kB)
     |████████████████████████████████| 65 kB 47 kB/s
Collecting six>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting decorator>=3.2.0
  Downloading decorator-4.4.2-py2.py3-none-any.whl (9.2 kB)
Collecting numpy
  Using cached https://www.piwheels.org/simple/numpy/numpy-1.19.0-cp37-cp37m-linux_armv7l.whl (10.5 MB)
Collecting appdirs>=1.4.0
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Building wheels for collected packages: pyopencl
  Building wheel for pyopencl (PEP 517) ... done
  Created wheel for pyopencl: filename=pyopencl-2020.2-cp37-cp37m-linux_armv7l.whl size=6540523 sha256=0015a38fed279c59763aaa15a5cc0f37498af9f4f8f1792cce8499dd89301ae1
  Stored in directory: /home/pi/.cache/pip/wheels/42/87/75/bff05b9f47820c782b4a23e40d2cdf07c8d23e758c7ab6d06e
Successfully built pyopencl
Installing collected packages: numpy, appdirs, decorator, six, pytools, pyopencl
Successfully installed appdirs-1.4.4 decorator-4.4.2 numpy-1.19.0 pyopencl-2020.2 pytools-2020.3.1 six-1.15.0
````

But as soon as numpy was imported, I got this error:

````
Traceback (most recent call last):
  File "/home/pi/opencl/pyOpenCL/.venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 22, in <module>
    from . import multiarray
  File "/home/pi/opencl/pyOpenCL/.venv/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/home/pi/opencl/pyOpenCL/.venv/lib/python3.7/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 2, in <module>
    import numpy as np
  File "/home/pi/opencl/pyOpenCL/.venv/lib/python3.7/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/home/pi/opencl/pyOpenCL/.venv/lib/python3.7/site-packages/numpy/core/__init__.py", line 48, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.7 from "/home/pi/opencl/pyOpenCL/.venv/bin/python"
  * The NumPy version is: "1.19.0"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libf77blas.so.3: cannot open shared object file: No such file or directory
````

**Comment by shazz** [comment]
Btw, I tried to subscribe to the mailing list:
A server error occurred. Please contact the administrator.

And thru a subscribe email, no reply....

**Comment by isuruf** [comment]
This is an issue with `piwheels.org` providing a broken numpy package. See https://blog.piwheels.org/how-to-work-out-the-missing-dependencies-for-a-python-package

**Comment by inducer** [comment]
> Btw, I tried to subscribe to the mailing list: A server error occurred. Please contact the administrator. And thru a subscribe email, no reply....

Thanks for the report, I'll take a look.

**Comment by shazz** [comment]
Inducer, could you fix the mailing list? I still have the same error.

I have a weird behavior with arrays of float16 but before creating a bug I'd like to check if I'm not doing anything wrong :)

**Comment by inducer** [comment]
I finally managed to investigate a bit, and it turns out mailing list subscription is broken because of [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=960072) currently. Feel free to create an issue for discussion in the meantime, forgoing the mailing list. Thanks for trying there first, and sorry about the trouble you encountered.

**Comment by shazz** [comment]
Ah ah no issue :) I Found the issue, I was mixing np.float16 and openCL float16.......... learning phase :)

I saw the beta of Github Discussions, could be a nice replacement to old mailman stuff.

Btw, I'd like to show you my little project using pyopencl to get your view... any better way to contact you?
