### ISSUE TITLE
int64 - uint32 (subtraction) not implemented correctly

### ISSUE THREAD

**Issue by mattwala** [inducer/pyopencl#355]
```python
>>> arr1 = cl.array.to_device(q, np.array([1], dtype=np.uint32))
>>> arr2 = cl.array.to_device(q, np.array([2], dtype=np.int64))
>>> arr2 - arr1
array([4294967297])
>>> (arr2 - arr1).dtype
dtype('int64')
>>> np.array([2], dtype=np.int64) - np.array([1], dtype=np.uint32)
array([1])
```

**Comment by mattwala** [comment]
Similar to loopy, the cause is implementing subtraction as `x + (-1) * y`.

I see three ways out of this:
- Implement a separate subtraction kernel in `pyopencl.elementwise`: `x - y`
- Cast operands to the the result dtype before performing a binary arithmetic operation: `(result_dtype)x + (-1)*(result_dtype)y`
- Do both: `(result_dtype)x - (result_dtype)y`. It's not clear whether this is equivalent to the one above.

The second/third options would be more intrusive changes but would be similar to what NumPy does.

**Comment by inducer** [comment]
IIUC, `(result_dtype)x + (-1)*(result_dtype)y` succeeds because it produces a two's-complement  `(-1)` of the correct bit width. Correct?

**Comment by mattwala** [comment]
> IIUC, `(result_dtype)x + (-1)*(result_dtype)y` succeeds because it produces a two's-complement `(-1)` of the correct bit width. Correct?

I haven’t tested it, but I think that’s how it should work.
