### ISSUE TITLE
build & push wheels for pypy3 to PyPI

### ISSUE THREAD

**Issue by yxliang01** [inducer/pyopencl#364]
It is great to figure out that pyopencl supports pypy3! However, currently wheels for pypy3 are not built and pushed to PyPI. It would be great to have pypy3 wheels.

Thanks

**Comment by inducer** [comment]
Thanks for the suggestion. All the scripts for building the wheels are in this repo, I'd be happy to consider a PR. See #264.

**Comment by yxliang01** [comment]
I have looked into it. I found the repo pypy/manylinux that has the pypy version of the docker image we are using now. However, I couldn't verify that it is from the pypy team, so unsure whether it is trustworthy. @inducer let me know if you think it is ok to use it? If so, the patch will be simple.

Alternatively, you can also maintain of a fork of it and audit the code there.

**Comment by inducer** [comment]
@isuruf You might have a better sense. Do you happen to know?

**Comment by isuruf** [comment]
Yes, `pypy/manylinux` is from the pypy team.

**Comment by yxliang01** [comment]
Shall we proceed to use that then? @inducer 
BTW, @isuruf I am curious how you verified it? Since the pypy wiki says that they don't use GitHub, although I know they meant mostly the pypy codebase.

**Comment by isuruf** [comment]
https://github.com/pypy lists Matti and Armin from the pypy team.

**Comment by inducer** [comment]
> Shall we proceed to use that then? @inducer

That makes sense to me.

**Comment by yxliang01** [comment]
So this has been implemented and merged in #491 . @inducer would you like to make a new release so that we can close this issue? :smile:

**Comment by inducer** [comment]
f983d40f562dfdf1ba202cf3e493ab5bc240f73c

**Comment by inducer** [comment]
(And https://pypi.org/project/pyopencl/2021.2.3/)
