### ISSUE TITLE
Profiling with Radeon Developer Panel throws error

### ISSUE THREAD

**Issue by philipp-mohr** [inducer/pyopencl#365]
Tried to capture a profile with the Radeon GPU Profiler (https://gpuopen.com/rgp/) but ended up with an error message in Python:
`    queue = CommandQueue(context)
pyopencl._cl.RuntimeError: CommandQueue failed: OUT_OF_HOST_MEMORY
`

What I did:
1. Started the  Radeon Developer Panel and connected to localhost.
2. Run following script:

```
from pyopencl import create_some_context
from pyopencl._cl import CommandQueue

context = create_some_context()
queue = CommandQueue(context)

```
The log messages of the developer panel are:
[RDP] Established connection to RDS within timeout.
[RDP] Connected successfully
[RDP] Received client connected from unknown client with id 1480.
[RDP] Received client halted from unknown client with id 1480.
[RDP] DeveloperPanelModel::AddClientInfo() - Processing halted client with id 1480: python.exe:4200 - AMD OpenCL Driver
[RDP] python.exe with clientId 1480 connected to driver control client in driver state HaltedOnDeviceInit
[RDP] DeveloperPanelModel::AddClientInfo() - Processing halted client with id 1480: python.exe:4200 - AMD OpenCL Driver
[RDP] DeveloperPanelModel::AddClientInfo() - Processing halted client with id 1480: python.exe:4200 - AMD OpenCL Driver
[RGP] DeveloperPanelModel::OnDriverStateChanged() - Handle processing for 'python.exe' (processId 4200, clientId 1480) in the HaltedOnDeviceInit driver state.
[RDP] Found 0 settings.
[RDP] EnableProfiling() for clientId 1480.
[RDP] Profile Settings: start = 0, end = 0, mode = 0, PSO = 0x0, flags = 0x0
[RDP] UpdateTraceParameters successful
[RDP] Enabled profiling for target executable 'python.exe', ProcessId = 4200.
[RDP] Can enable profiling for client ID 1480
[RDP] Set profiling flag for ProcessId = 4200 (client ID 1480) to true.
[RDP] Capture profile button is enabled because the target application is profilable and there is no profile in progress.
[RDP] DeveloperPanelModel::OnDriverStateChanged() - Update client run status.  Current driver state is HaltedOnDeviceInit for process 'python.exe', ProcessId = 4200
[RDP] Advance to next driver state.  Current driver state is HaltedOnDeviceInit for process 'python.exe', ProcessId = 4200
[RDP] Step driver for process 'python.exe', ProcessId = 4200
[RDP] DeveloperPanelModel::NextDriverState() - Query Driver status failed (driver control client likely disconnected)
[RDP] Client with Id 1480 has disconnected.
[RDP] Capture profile button has been disabled because the application is not profilable.

Using pyopencl‑2020.2.1+cl21‑cp38‑cp38‑win_amd64.whl from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl

**Comment by inducer** [comment]
What happens for an equivalent C program? (You can use [this](https://github.com/hpc12/tools/blob/master/cl-demo.c) to try if you like.)

**Comment by philipp-mohr** [comment]
Thanks for your proposal. I compiled the cl_demo.c project for Windows. Unfortunately I get the same error message when running the .exe application while the Radeon Developer Panel is connected to localhost.

*** 'clCreateCommandQueue' in '...\cl-helper.c' on line 352 failed with error 'out of host memory'.

**Comment by inducer** [comment]
Thanks for trying this and reporting back. Given what you said, this doesn't seem to be an issue specific to pyopencl, so I'll go ahead and close this. But you could try the [PyOpenCL mailing list](https://lists.tiker.net/postorius/lists/pyopencl.tiker.net/) to see if anyone has had more success with the Radeon tools.

**Comment by EvgeniyPeshkov** [comment]
Hello @piveloper , try [CLtracer](https://www.cltracer.com/) profiler. I've checked, it works with PyOpenCL.

**Comment by philipp-mohr** [comment]
Thanks for the hint. However it does not seem to work for my configuration. I can start the application by clicking "start", but it produces no trace. Any idea how to fix it?
![ClTraceNotWorking](https://user-images.githubusercontent.com/22196896/92389646-c3392500-f119-11ea-98fa-e0bd689c3ef1.png)

I use a Radeon VII Graphics card.

cl_trace_example.py
```
from __future__ import absolute_import, print_function
import numpy as np
import pyopencl as cl

a_np = np.random.rand(50000).astype(np.float32)
b_np = np.random.rand(50000).astype(np.float32)

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

mf = cl.mem_flags
a_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=a_np)
b_g = cl.Buffer(ctx, mf.READ_ONLY | mf.COPY_HOST_PTR, hostbuf=b_np)

prg = cl.Program(ctx, """
__kernel void sum(
    __global const float *a_g, __global const float *b_g, __global float *res_g)
{
  int gid = get_global_id(0);
  res_g[gid] = a_g[gid] + b_g[gid];
}
""").build()

res_g = cl.Buffer(ctx, mf.WRITE_ONLY, a_np.nbytes)
prg.sum(queue, a_np.shape, None, a_g, b_g, res_g)

res_np = np.empty_like(a_np)
cl.enqueue_copy(queue, res_np, res_g)

# Check on CPU with Numpy:
print(res_np - (a_np + b_np))
print(np.linalg.norm(res_np - (a_np + b_np)))
assert np.allclose(res_np, a_np + b_np)
```

**Comment by EvgeniyPeshkov** [comment]
Do you use CLtracer on Windows or Linux OS?

**Comment by philipp-mohr** [comment]
On Windows 10 64 Bit

**Comment by EvgeniyPeshkov** [comment]
Have you already updated to Windows 10 version 2004 and also have Intel GPU OpenCL runtime?

**Comment by philipp-mohr** [comment]
I have Intel GPU OpenCl runtime installed. And I use the driver from AMD:
https://www.amd.com/en/support/graphics/amd-radeon-2nd-generation-vega/amd-radeon-2nd-generation-vega/amd-radeon-vii

Yes, I use Windows Version 2004.

**Comment by EvgeniyPeshkov** [comment]
@piveloper , sorry for the delay, I needed to re-check everything.
I also experienced the same issue as you and that happened right after the update to version 2004.
This bug [is known](https://www.cltracer.com/docs#troubleshooting) and I believe it will be fixed in the next release of CLtracer.
I've installed AMD driver that you've mentioned, I have a much older GPU though.
I have two GPUs, Intel's embedded and AMD's discrete. If "Intel Graphics Driver" (that also includes CL runtime) is installed applications start but profiling info is not captured. When I uninstall "Intel Graphics Driver" everything works fine. I've even checked the PyOpenCL example you've posted earlier.
Maybe I'll be worth to check that Intel's OpenCL runtime is not installed using [clinfo](https://ci.appveyor.com/api/projects/oblomov/clinfo/artifacts/clinfo.exe?job=platform%3a+x64)?

**Comment by philipp-mohr** [comment]
I just checked and I had the Intel GPU runtime installed. However after uninstalling and restarting the computer, I still get an empty trace.

**Comment by EvgeniyPeshkov** [comment]
Minor update: continuing experiments, I've found that Intel Graphics Driver itself is the cause of the issue. So it doesn't mean that everything will work if clinfo shows no Intel GPU. And it's very likely that after restart Windows installs driver back, at least it did it for me (=.
But it seems I've found a temporary solution - to disable Intel GPU in Device Manager.

![image](https://user-images.githubusercontent.com/50870158/92400930-5b90d300-f135-11ea-8411-64fd9f27c754.png)

**Comment by philipp-mohr** [comment]
On my server the Intel HD card is not there. Maybe its because I have three Radeon cards installed.
![grafik](https://user-images.githubusercontent.com/22196896/92401809-b83cbf80-f12e-11ea-9109-f956faadf036.png)

**Comment by EvgeniyPeshkov** [comment]
I don't think the number of Radeon cards is the issue. Maybe some part of Intel's driver is still there or e.g. there is AMD's platform and devices, but ICD is still from Intel. Try to also check a registry at `HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenCL\Vendors` where all OpenCL vendors are listed and make sure there are no Intel's dlls. Maybe re-installation of AMD driver after Intel's runtime is removed will help.
Meanwhile, I've rolled Windows version back to 1904, and everything works. I've also checked that the issue with Intel's runtime appears on one of the newest GPU as well as 10 years old. So it clearly some kind of software bug that came out on Windows 2004.
PS: Very-very nice machine btw (=.

**Comment by philipp-mohr** [comment]
There was indeed a .dll. I deleted it. Unfortunately, CL tracer is still empty.

Thanks :) And I want to get most out of it - hopefully some update will fix the issue such that I can use your profiler for that purpose.

![2020-09-15 13_22_16-FREYR - Remotedesktopverbindung](https://user-images.githubusercontent.com/22196896/93206834-54cc1680-f75a-11ea-9d76-98a2290164d9.png)

**Comment by EvgeniyPeshkov** [comment]
Hello @piveloper ! Perfect timing (=. A new version is already available, published half an hour ago.
It fixes problems on Windows 10 ver. 2004. At least, I've checked on all machines I've access to.
You can download a new version or use an auto-update right from the app.

**Comment by philipp-mohr** [comment]
Got the update installed. But it changed nothing for me :( If you like, you can take a look via team viewer? You can contact me by e-mail: piveloper@gmail.com
