### ISSUE TITLE
Could you please fix CL_DEVICE_TOPOLOGY_AMD?

### ISSUE THREAD

**Issue by pigsboss** [inducer/pyopencl#371]
I need to identify AMD GPUs according to their hardware topology in order to scatter MPI instances in a multiple-GPUs host. I found the `CL_DEVICE_TOPOLOGY_AMD` (0x4037) constant from OpenCL API which could be helpful. But `device.get_info(0x4037)` throws `INVALID_VALUE` error. I found the corresponding switch-case clause has been commented out in wrap_cl.hpp as 
```
/* FIXME
#ifdef CL_DEVICE_TOPOLOGY_AMD
          case CL_DEVICE_TOPOLOGY_AMD:
#endif
*/
```
I tried to fix it although in a dirty & ugly way:
```
#ifdef CL_DEVICE_TOPOLOGY_AMD
          case CL_DEVICE_TOPOLOGY_AMD:
            {
              std::vector<cl_char> result;
              PYOPENCL_GET_VEC_INFO(Device, m_device, param_name, result);
              PYOPENCL_RETURN_VECTOR(cl_char, result);
            }
#endif
```
And as a result in my Python code I can play with the returned array of chars:
```
res=device.get_info(0x4037)
type=res[0]+256*(res[1]+256*(res[2]+256*res[3]))
bus=res[-3]
dev=res[-2]
fun=res[-1]
```
Could you please fix this? And I'm also curious about what happened when you commented this out at the first place...

**Comment by inducer** [comment]
Could you try #373 and let me know if that works for you?

**Comment by pigsboss** [comment]
> Could you try #373 and let me know if that works for you?

My pleasure. I've switched to `origin/more-amd-device-queries` branch and re-installed pyopencl package. Now I can confirm that `device.topology_amd` is enabled and the returned  `DeviceTopologyAmd` instance is consistent with the results from `clinfo`.

**Comment by inducer** [comment]
Great, thanks! I'll merge that then.
