### ISSUE TITLE
Tagging read-only SVM buffer with cl.SVM throws an exception

### ISSUE THREAD

**Issue by dsawczuk-int** [inducer/pyopencl#372]
Hi,

When I try to tag SVM read-only buffer with cl.SVM wrapper (in order to copy memory) the following exception is thrown: 
`ValueError: buffer source array is read-only`. I do not see any restrictions regarding SVM read-only buffers in documentation. Is this expected behaviour?

I am using Python 3.6.7 and pyopencl==2020.2.1.

Reproduction code:
```
import pyopencl as cl
import numpy as np

ctx = cl.create_some_context()
svm_buf_arr = cl.svm_empty(ctx, cl.svm_mem_flags.READ_ONLY, 10, np.int32)
svm_buf = cl.SVM(svm_buf_arr) # throws the exception
print("OK")
````

Traceback:
```
Traceback (most recent call last):
  File "aa.py", line 6, in <module>
    svm_buf = cl.SVM(svm_buf_arr) # throws the exception
  File "<path>python3.6/site-packages/pyopencl/__init__.py", line 1215, in svm_init
    svm_old_init(self, mem)
ValueError: buffer source array is read-only
```

**Comment by inducer** [comment]
Could you try #375?

**Comment by dsawczuk-int** [comment]
Thank you! It works now!

Do you mind if I ask when do you plan to release the next version of pyopencl (with this fix)?

**Comment by inducer** [comment]
> Thank you! It works now!

Thanks for checking. I'll close this.

> Do you mind if I ask when do you plan to release the next version of pyopencl (with this fix)?

2020.2.2, hot off the presses just for you.
