### ISSUE TITLE
image allocation doesn't work 

### ISSUE THREAD

**Issue by andrea993** [inducer/pyopencl#392]
I can't use `image_from_array()` or other functions that allocate images like `cl.Image()`

```
import pyopencl as cl
import numpy as np
from PIL import Image

img = Image.open('test_new.jpg').convert('RGB') 
W = img.width
H = img.height
npimg = np.array(img)
plats = cl.get_platforms()
ctx = cl.Context(plats[0].get_devices())  
queue = cl.CommandQueue(ctx)
img_in_g = cl.image_from_array(ctx, npimg, 3)
```

I get the error:
```

  File "untitled1.py", line 14, in <module>
    img_in_g = cl.image_from_array(ctx, npimg, 3)

  File "/usr/lib/python3.8/site-packages/pyopencl/__init__.py", line 1858, in image_from_array
    return Image(ctx, mode_flags | mem_flags.COPY_HOST_PTR,

  File "/usr/lib/python3.8/site-packages/pyopencl/__init__.py", line 1000, in image_init
    image_old_init(self, context, flags, format, shape,

LogicError: clCreateImage2D failed: INVALID_OPERATION
```
I've not problems with standard buffers instead of images.
I tried with both my opencl devices and the result is the same.

I attach my clinfo
[myclinfo.txt](https://github.com/inducer/pyopencl/files/5448541/myclinfo.txt)

**Comment by inducer** [comment]
Cannot reproduce. Works fine on Nvidia. If you're trying to run on POCL, note that it doesn't have image support. Intel CL does have image support on the CPU, but it doesn't seem to like this particular image format.

For the Intel CPU CL runtime, look [here](https://github.com/intel/llvm/releases/tag/2020-09) (` oclcpuexp-2020.11.8.0.27_rel.tar.gz`)

**Comment by andrea993** [comment]
The problem is that it doesn't work on my AMD GPU that sould support images, or at least attached clinfo says yes.

**Comment by inducer** [comment]
Do the image-related tests in `test/test_wrapper.py` work?

(Select a GPU to run on by setting the env var `PYOPENCL_TEST=amd:name` (i.e. some any-case substring of your plat/dev name))
