### ISSUE TITLE
enqueue_fill_buffer issues on NVIDIA for nbytes >= 2**31

### ISSUE THREAD

**Issue by zachjweiner** [inducer/pyopencl#395]
I'm not sure whether this is a problem in the wrapper or just in NVIDIA's driver, but calls to `enqueue_fill_buffer` (e.g., by [`pyopencl.array.zeros`](https://github.com/inducer/pyopencl/blob/4e2e4f3150c331680e6d9e36c59290411e4a0c40/pyopencl/array.py#L1287)) either hang or result in errors when `nbytes >= 2**31`. On Pascal the call just hangs and on Volta the call returns but throws an error at the OpenCL API call (e.g., clBuildProgram failure with <unknown error -9999>), so far as I can tell. (I've reproduced this on numerous machines and driver versions.)

According to the [spec](https://www.khronos.org/registry/OpenCL/specs/3.0-unified/html/OpenCL_C.html#_footnotedef_4) the size parameter is supposed to be a 64 bit integer (based on `device.address_bits`), but alas.

```python
import pyopencl as cl
import pyopencl.array as cla
ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

print(ctx.devices[0].address_bits) # prints 64 on NVIDIA, so size_t should be 64 bit

x = cla.empty(queue, shape=(2**28,), dtype='float64')
x[...] = 0.
print("I make it here")

y = cla.zeros(queue, shape=(2**28,), dtype='float64')
print("I don't make it here")
```

Regardless of the source of the error, a simple workaround is to just use `Array.fill` instead whenever the platform is NVIDIA and `nbytes >= 2**31`. Is that an acceptable solution?

**Comment by inducer** [comment]
Yeah, I'd be happy to look at a PR that does that. Make sure to leave a reference (in a comment) to this issue.
