### ISSUE TITLE
get_platforms() returns 2 platforms on a single nVidia RTX 3090 GPU, causes kernel crash if run on both devices simultaneously

### ISSUE THREAD

**Issue by yliu88au** [inducer/pyopencl#418]
CL function get_platforms() returns 2 platforms on a single nVidia RTX 3090 GPU, each platform has a device attached to it. If I try to run staff on these two devices simultaneously, python kernel will crash. However, if I run program on any single device only, it will be fine.

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own. Sorry!

**Comment by yliu88au** [comment]
@inducer I believe this is a bug in get_platforms(), I have no issue with running it, with adaption of my program.

**Comment by inducer** [comment]
What does `clinfo` print?

**Comment by yliu88au** [comment]
After a thorough check, I believe that cl.get_platforms() mis-reported one of the GPU card. My system has two GPUs, one is "GeForce RTX 3090", the second one is "Quadro K5000" The call `cl.get_platforms()` gets two platforms as it should:
  `[<pyopencl.Platform 'NVIDIA CUDA' at 0x2e5526fb160>,
   <pyopencl.Platform 'NVIDIA CUDA' at 0x2e5526fabc0>]`

However, if I run

`for item in cl.get_platforms():
     print(item.get_devices())`

I got 

`[<pyopencl.Device 'GeForce RTX 3090' on 'NVIDIA CUDA' at 0x2e5526fa710>]
[<pyopencl.Device 'GeForce RTX 3090' on 'NVIDIA CUDA' at 0x2e5526fadf0>]`

Both GPU are reported as "GeForce RTX 3090", and the "Quadro K5000" was not reported.

My OS is Windwos 10, Python 3.8.5, with nVidia driver 460.89

**Comment by inducer** [comment]
What does `clinfo` print?

**Comment by yliu88au** [comment]
Please forgive me, I am new in opencl (pyopencl). I don't seem to be able to run "clinfo" from my "ipython" command line.

**Comment by inducer** [comment]
https://github.com/Oblomov/clinfo

**Comment by yliu88au** [comment]
[clinfo_results.txt](https://github.com/inducer/pyopencl/files/5833835/clinfo_results.txt)
This is the results. It seems no "Quadro K5000" to be seen!

**Comment by yliu88au** [comment]
The following confirms K5000 can be seen by nvidia-smi:

`!nvidia-smi`
Tue Jan 19 16:48:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.89       Driver Version: 460.89       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce RTX 3090   WDDM  | 00000000:03:00.0 Off |                  N/A |
| 44%   54C    P8    27W / 350W |    940MiB / 24576MiB |     13%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro K5000       WDDM  | 00000000:22:00.0 Off |                    0 |
| 30%   40C    P8    21W / 137W |    174MiB /  3584MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1768    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A     14108    C+G   ...root\Office16\OUTLOOK.EXE    N/A      |
|    0   N/A  N/A     16452    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A     21092    C+G   ...bin\win64\jcef_helper.exe    N/A      |
|    0   N/A  N/A     24084    C+G   ...me\Application\chrome.exe    N/A      |
|    0   N/A  N/A     35184    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A     36412    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
|    0   N/A  N/A     40652    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A     41304    C+G   ...020a\bin\win64\MATLAB.exe    N/A      |
|    0   N/A  N/A     41324      C   ...a3\envs\Tigre2\python.exe    N/A      |
|    1   N/A  N/A      1768    C+G   Insufficient Permissions        N/A      |
|    1   N/A  N/A     13732    C+G   ...zf8qxf38zg5c\SkypeApp.exe    N/A      |
|    1   N/A  N/A     20020    C+G   ...bbwe\Microsoft.Photos.exe    N/A      |
|    1   N/A  N/A     20256    C+G   ...b3d8bbwe\WinStore.App.exe    N/A      |
|    1   N/A  N/A     21344    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    1   N/A  N/A     38496    C+G   Insufficient Permissions        N/A      |
|    1   N/A  N/A     39336    C+G   Insufficient Permissions        N/A      |
+-----------------------------------------------------------------------------+

**Comment by inducer** [comment]
> [](https://github.com/inducer/pyopencl/files/5833835/clinfo_results.txt)
> This is the results. It seems no "Quadro K5000" to be seen!

That means this is a problem of your underlying OpenCL implementation. Any application using OpenCL would have this view of your system. There isn't much that PyOpenCL can do about that. Sorry!

**Comment by yliu88au** [comment]
Understood. Have to wait for nVidia to fix their version of opencl......., I just installed newest Intel Opencl SDK, the results are the same. Thanks for your help.
