### ISSUE TITLE
wheels for windows on pypi

### ISSUE THREAD

**Issue by konserw** [inducer/pyopencl#420]
Hi!
Would you please consider shipping wheels for windows on pypi? I know this exist: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopencl but it would save a lot of trouble for windows people if installing from pip would "just work" :) 
I suppose asking for windows wheels for pytho2.7 would be too much? :)

**Comment by inducer** [comment]
I would welcome a contributed CI job! Maybe the existing Linux wheel build can help as an example.

**Comment by haesleinhuepf** [comment]
I would also be interested in this! Most of my collaborators/users typically don't have buildtools installed and struggle with pyopencl installation on Windows from time to time.

@inducer Which CI are you using? I'd be happy to take a look and see if I can make it work for Windows :-)

**Comment by inducer** [comment]
Thanks for the offer! As of #421, it's just Github Actions all around, which AFAIK supports Windows just fine.

**Comment by inducer** [comment]
#559
