### ISSUE TITLE
Impossible cast error at program compilation

### ISSUE THREAD

**Issue by aodenis** [inducer/pyopencl#444]
Hello !
The compile function of a pyopencl program seems to always crash when its header argument is not an empty list, throwing a RuntimeError due to an impossible C++/Python cast.
According to the code, in the `(name, program)` tuples that are expected in the header argument, `program` is expected to be a `_cl._Program` object, rather than a front end `cl.Program` as in the documentation. The function works well when `program._get_prg()` is used instead of `program`.

**Comment by inducer** [comment]
Thanks for the report!
