### ISSUE TITLE
Pipe creation is broken

### ISSUE THREAD

**Issue by readysloth** [inducer/pyopencl#464]
As i understand, according to [khronos manual](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/clCreatePipe.html), argument `properties` of `clCreatePipe` should be `NULL` for now.

> Errors
> clCreatePipe returns a valid non-zero pipe object and errcode_ret is set to CL_SUCCESS if the pipe object is created successfully. Otherwise, it returns a NULL value with one of the following error values returned in errcode_ret:
> ...
>  _CL_INVALID_VALUE if properties is not NULL._

And in [`create_pipe`](https://github.com/inducer/pyopencl/blob/4e7c3250b6c3c0ef12635070966bae901b09bac2/src/wrap_cl.hpp#L3153) you enlarge `props` by one, appending zero at the end of `props`. Because of that, in call [`clCreatePipe`](https://github.com/inducer/pyopencl/blob/4e7c3250b6c3c0ef12635070966bae901b09bac2/src/wrap_cl.hpp#L3171) [`PYOPENCL_STACK_CONTAINER_GET_PTR`](https://github.com/inducer/pyopencl/blob/4e7c3250b6c3c0ef12635070966bae901b09bac2/src/wrap_cl.hpp#L127) will return not `nullptr`, but valid pointer to collection.

This is mainly because user cannot pass `None`/`nullptr` from ctypes or do not specify `properties` in `pyopencl.Pipe(context, flags, packet_size, max_packets, properties)`. If user pass empty collection, he will recieve error above.

**Comment by inducer** [comment]
Thanks for the report! Could you take a look at #465 to see if it addresses the issue?

**Comment by readysloth** [comment]
Thank you for your work! Now i can create pipes as i wanted to :^)
