### ISSUE TITLE
Pipe always have zero packets available

### ISSUE THREAD

**Issue by readysloth** [inducer/pyopencl#466]
I made example program to test pipe read/write and faced problem that always have zero packets available...
What am I doing wrong? I used [`get_pipe_num_packets`](https://www.khronos.org/registry/OpenCL/sdk/2.0/docs/man/xhtml/get_pipe_num_packets.html)

```python
import numpy as np
import pyopencl as cl

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

pipe = cl.Pipe(ctx, cl.mem_flags.READ_WRITE, np.int32(1), np.int32(1024))
arr = np.empty((10,1), dtype=np.byte)

text = """
__kernel void pipe_test(write_only pipe char gray_pipe)
    {
        int num_packets = get_pipe_num_packets(gray_pipe);
        printf("packets available: %d\\n", num_packets);
    }
"""

prg = cl.Program(ctx, text).build(options=['-cl-std=CL2.0'])
prg.pipe_test(queue, arr.shape, None, pipe)

```

**Comment by inducer** [comment]
I've never used pipes, I'm not sure I can be much help. However my impression is that you need to write packets into a pipe from one work item in order for them to be available in another?

**Comment by inducer** [comment]
At any rate, what you report seems to mostly concern the ICD (i.e. the driver/implementation of CL) that you're using, not so much PyOpenCL.

**Comment by readysloth** [comment]
I guess you are right. Thank you.
