### ISSUE TITLE
Abort after "ctx = cl.create_some_context()"

### ISSUE THREAD

**Issue by admanero** [inducer/pyopencl#477]
Hi

  I have installed pyopencl from conda as described here:
  https://documen.tician.de/pyopencl/misc.html
  
  And then I go to the examples. I start a python interpreter at conda  and start a session to try it out , after entering the following line:  "ctx = cl.create_some_context()"   I get an abort. See below. 
  It is Linux, CentOS 8  with Python 3.8.5 installed from Anaconda with environment "py38" activated.
   Any hint or suggestion of what might be wrong would be much appreciated. I am newby at OpenCL although I have a bit of experience running CUDA and pycuda with an Nvidia card.
  
  (py38) [admpy@ThermalBox anaconda3]$ ./bin/python3
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import pyopencl as cl
>>> a_np = np.random.rand(50000).astype(np.float32)
>>> b_np = np.random.rand(50000).astype(np.float32)
>>> ctx = cl.create_some_context()
Abort was called at 42 line in file:
/builddir/build/BUILD/compute-runtime-21.18.19737/shared/source/built_ins/built_ins.cpp
Aborted (core dumped)

**Comment by inducer** [comment]
From your description, it appears that you're trying to mix Anaconda and conda forge. (I.e. you didn't use `miniforge` to set up conda as the instructions specify.) That's not supposed to work, and I'm not surprised it doesn't.
