### ISSUE TITLE
Error when building wheel Exit Status 1

### ISSUE THREAD

**Issue by jseder5** [inducer/pyopencl#482]
I have been trying to install pyopencl and have tried several methods. I have tried using pip install pyopencl and always receive the error "Building wheel for pyopencl (setup.py) ... error ERROR: Command errored out with exit status 1:". 

Anytime that I have tried to install using the conda conda-forge option there seems to be many package inconsistencies, failed solves, and seemingly endless installation time with little to no progress.  

I have also manually put the windows wheels in to the site-packages folder with no change.

Any help would be appreciated

**Comment by inducer** [comment]
If you'd like help with the conda install process, please paste the output of [these commands](https://documen.tician.de/pyopencl/misc.html#installing-pyopencl) into a gist and link it here.

**Comment by jseder5** [comment]
https://gist.github.com/jseder5/b6263a917d4b30a08d1f2c4e16c4ccaa#file-gistfile1-txt
