### ISSUE TITLE
ci.feat(wheel & pypi): use cibuildwheel

### ISSUE THREAD

**Issue by yxliang01** [inducer/pyopencl#488]
cibuildwheel from PyPA is a convenient solution for building wheels with a few command and consistently for Linux, Windows and Mac and also for PyPi!. So, can be very useful to use it rather than directly using manylinux Docker (it will then be indirectly used seems like from its doc). They have also provided GitHub actions that we can directly use if this is wanted.

This potentially closes #364 , #406 and #420 (Note, there's no official support for py2 as requested in the issue).

**Comment by inducer** [comment]
Thanks for the suggestions. Contributions along these lines are definitely welcome!
