### ISSUE TITLE
"No constructor defined" error

### ISSUE THREAD

**Issue by ma-sadeghi** [inducer/pyopencl#492]
I installed `pyopencl` on a fresh conda virtualenv, but when running `pyopencl.device_info()` I get:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: pyopencl._cl.device_info: No constructor defined!
```
Does that mean my GPU driver was not found?

PS. I also tried installing `ocl-icd-system` but didn't help.

**Comment by inducer** [comment]
No. `device_info` is a namespace for constants. It's not meant to be instantiated. Please follow the [examples](https://github.com/inducer/pyopencl/tree/main/examples).
