### ISSUE TITLE
Compiling configuration

### ISSUE THREAD

**Issue by marromlam** [inducer/pyopencl#510]
I have some set of device functions and kernels in some .c files, which I can perfectly compile when I compile them with pyopencl. For developing purposes I would like to be able to compile those files together with gcc instead of using pyopencl.
So I was just trying to do that, only importing some of my headers, and I got errors related to `float2` not defined among others.

So, my question is, is there any way I can just do,
```
gcc main.c -o main ...
```
such that I can attain what I wanted.

Maybe this is already documented, but I could not find it. Thank you

**Comment by inducer** [comment]
This issue tracker is for bugs, not technical support. Please send a message to the mailing list for tech support. One reason for this request is that I am typically the only one who sees issue email, and I am unable to handle the tech support load on my own.

**Comment by marromlam** [comment]
Can you please tell me which mailing list?
Thanks a lot

**Comment by inducer** [comment]
https://lists.tiker.net/hyperkitty/list/pyopencl@tiker.net/
