### ISSUE TITLE
Unreleased/untagged version of pyopencl is now on PyPI?

### ISSUE THREAD

**Issue by litghost** [inducer/pyopencl#520]
Looks like someone uploaded a source version of 2021.2.9 to PyPI but didn't tag 2021.2.9 in this repo?  End result appears to be that 2021.2.9 is missing its binary wheels in PyPI?

**Comment by inducer** [comment]
Whoops. Missed the tag push. Now pushed.

**Comment by inducer** [comment]
Thanks for letting me know.
