### ISSUE TITLE
Memory issue on cauculations of pyopencl.array.Array

### ISSUE THREAD

**Issue by TsXor** [inducer/pyopencl#634]
**Describe the bug**
PyOpenCl tend to use lots of memory when builtin operators are used frequently.

**To Reproduce**
```
x = somewhatarray
for _i in range(100):
    y = x**2
```
and you will see the memory usage keep increasing.

**Expected behavior**
Memory usage will increase and decrease when `y = x**2` is executed every time.

**Environment (please complete the following information):**
 - OS: [Windows 10]
 - ICD Loader and version: [?]
 - ICD and version: [?]
 - CPU/GPU: [AMD R7 250]
  - Python version: [3.9]
  - PyOpenCL version: [2022.2.3]

**Additional context**
What python do in the >=2th execution of `y = x**2`:
1. python calls the `__pow__` method of x and got the result of `x**2`, let's call it `v` and call the previous array `y` points to `v_old`.
2. `v` is assigned to `y`, the refcount(PY) of `v_old` drops to 0, python GC the `v_old` object.

So now I add the `__del__` method of pyopencl.array.Array, which will be called when python GC an object of this class:
```python
    def __del__(self):
        self.base_data.release()
```

However, this will not solve the problem: memory usage still keep increasing.

I let `__del__` print out how the OpenCL refcount has changed:
```python
    def __del__(self):
        ref_bd = self.base_data.get_info(cl.mem_info.REFERENCE_COUNT)
        self.base_data.release()
        ref_ad = self.base_data.get_info(cl.mem_info.REFERENCE_COUNT)
        print('An array is deleted in PY, its CL ref %d -> %d'%(ref_bd, ref_ad))
```
And I found that the refcount(CL) of `v_old` drops from 2 to 1.

I dug deeper, and found that the refcount(CL) increases when `knl(queue, gs, ls, *args, wait_for=wait_for)` is executed in the `elwise_kernel_runner` of `array.py`, but it doesn't decrease as expected when magic methods like `__pow__` ends.

Yet something strange emerge: If I keep doing `print(x**2)`, memory usage will not keep increasing, and `__del__` shows that when the `v_old` is GC-ed, its refcount(CL) drops from 1 to 0 as expected! However, observation showed that refcount(CL) still increases in this situation. Where did it decrease???

**Comment by TsXor** [comment]
I tried to let `__del__` wait for the events, and surprisingly, it worked:
```python
    def __del__(self):
        self.finish()
        self.base_data.release()
```
all arrays let their refcount(CL) drop to 0 when they are GC-ed!

**Comment by TsXor** [comment]
I propose to add a switch for the constructor of `pyopencl.array.Array`. For example, `pygc`. When it is `True`, `__del__` will work, or `__del__` will immediately return.

**Comment by TsXor** [comment]
I think we should add it because manually freeing memory can sometimes be ugly.
For example, manual freeing of mem for
```python
x = somewhatarray
y = x
for _i in range(100):
    y = y*2
```
should be:
```python
x = somewhatarray
y = x
for _i in range(100):
    y_bak = y
    y = y_bak*2
    y_bak.finish()
    y_bak.base_data.release()
    del y_bak
```

**Comment by inducer** [comment]
As far as I can tell, this is all behaving as designed. Please point if that is not so, in your view.
