### ISSUE TITLE
Windows Intel CL Github CI fails

### ISSUE THREAD

**Issue by inducer** [inducer/pyopencl#690]
https://github.com/inducer/pyopencl/actions/runs/5312788354/jobs/9745319723

It seems that miniforge3 no longer installs into the specified location. I went so far as trying this in a local Windows VM, where it (seemingly) worked OK. Kind of stumped.

cc @isuruf

**Comment by isuruf** [comment]
Fixed with https://github.com/inducer/ci-support/commit/79644714f297f20c23dc8a5a8212732c920a053b and the new miniforge release.

**Comment by inducer** [comment]
Thank you very much for your help!
