### ISSUE TITLE
`CMakeLists.txt` file missing in PyPI source dist

### ISSUE THREAD

**Issue by yubrajbhoi** [inducer/pyopencl#747]
**Describe the bug**
`CMakeLists.txt` is present here but it is missing from the source distribution in PyPI (`pyopencl-2024.2.tar.gz`). It is required to build the `_cl` library with nanobind.

**To Reproduce**

Try to build using the source distribution from PyPI.

**Expected behavior**
We should be able to build using the source distribution.

**Environment (please complete the following information):**
 - OS: Linux
 - ICD Loader and version: ocl-icd 2.3.2
 - ICD and version: OpenCL 3.0
 - CPU/GPU: Intel CPU and iGPU
  - Python version: 3.11
  - PyOpenCL version: 2024.2

**Comment by inducer** [comment]
I find this puzzling; in my local checkout, `CMakeLists.txt` gets included in the source package, but apparently not in CI. I haven't figured out why, but I guess #748 is simple enough of a fix.

**Comment by inducer** [comment]
https://github.com/inducer/pyopencl/releases/tag/v2024.2.1 should show up on the package index soon-ish.

And thanks for the report.
