### ISSUE TITLE
pyopencl.compyte missing in pyopencl-2024.2.4.tar.gz

### ISSUE THREAD

**Issue by cgohlke** [inducer/pyopencl#765]
The `pyopencl.compyte` directory is missing in the source distribution on [PyPI](https://pypi.org/project/pyopencl/#files).

`import pyopencl` fails with `ModuleNotFoundError: No module named 'pyopencl.compyte'` if installed from source distribution.

**Comment by inducer** [comment]
Thanks for letting me know. I've yanked the release.

**Comment by inducer** [comment]
#766 should deal with this. I'll roll a new release once this is in.

**Comment by cgohlke** [comment]
Thank you.
