### ISSUE TITLE
2024.2.5 is Broken

### ISSUE THREAD

**Issue by amirmasoudabdol** [inducer/pyopencl#767]
**Describe the bug**
There is no `sdist.exclude`, and as a result the TOML file is ill defined and the `pip install ` fails. 

**To Reproduce**
1. Try installing the package
2. You'll get an error indicating that the line 100 of the TOML file contains an error. 

**Expected behavior**
`pip install` should work. 

**Environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - PyOpenCL version: 2024.2.5

**Additional context**
Sorry that I couldn't provide more info, I'm filling this on the go via the iOS app. But, as far as I understood `tool.scikit-build` doesn't understand the `sdist.exclude` which results in:

```
pip._vendor.pytoml.core.TomlError: /tmp/pip-install-jyqer1wa/pyopencl/pyproject.toml(100, 1): msg
```

**Comment by matthiasdiener** [comment]
I can't reproduce this issue. Could you mention the versions of your `pip` and `tomli` packages? `sdist.exclude` is defined here: https://scikit-build-core.readthedocs.io/en/latest/configuration.html#configuring-source-file-inclusion. Also, could you provide the full build output and the command you use to install?

**Comment by amirmasoudabdol** [comment]
Hmm, then I might have missed something! Let me investigate and I come back to you! 😊

**Comment by amirmasoudabdol** [comment]
I checked, and I see that I’m using `pip==20.0.2` and `tomli==2.0.1`. I see that I cannot reproduce it with `pip>=24.0`, so is this the `pip` issue you think?

**Comment by matthiasdiener** [comment]
I was able to successfully install this pyopencl release with Python 3.10.14 and pip 20.1.1/20.3.4, so there is maybe another issue in the environment

**Comment by amirmasoudabdol** [comment]
I’m baffled, but you are right, it’s most likely something else on my side. I’ll close the issue then. Thanks for looking into it and your input! 🙏🏼
