### ISSUE TITLE
Invoker cache created and written to even when PYOPENCL_NO_CACHE=1

### ISSUE THREAD

**Issue by hvenev-insait** [inducer/pyopencl#773]
When `PYOPENCL_NO_CACHE=1`, the invoker cache is always created when importing `pyopencl.invoker`. Furthermore, it is written to every time an invoker is created. `PYOPENCL_NO_CACHE` only seems to control reads. 

**To Reproduce**
1. Delete all caches.
2. Run `python3` with the `PYOPENCL_NO_CACHE` environment variable set to `1`.
3. Import `pyopencl` and run a kernel.
3. Observe that the invoker cache now exists.

**Expected behavior**
When `PYOPENCL_NO_CACHE=1`, no attempts should be made to read caches, write caches, create caches, lock caches, or check whether caches exist.

**Environment:**
 - OS: Linux
 - ICD Loader and version: ocl-icd 2.3.2
 - ICD and version: pocl 6.0, NVIDIA 550.90.07
 - x86-64, NVIDIA A6000
  - Python version: 3.12.4
  - PyOpenCL version: 2024.1

**Comment by matthiasdiener** [comment]
This should be fixed in 2024.2, see e.g. #736.

**Comment by hvenev-insait** [comment]
Yes, it looks like that fixes it.
